// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package current_identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openziti/edge/rest_model"
)

// GetCurrentIdentityOKCode is the HTTP code returned for type GetCurrentIdentityOK
const GetCurrentIdentityOKCode int = 200

/*GetCurrentIdentityOK The identity associated with the API Session used to issue the request

swagger:response getCurrentIdentityOK
*/
type GetCurrentIdentityOK struct {

	/*
	  In: Body
	*/
	Payload *rest_model.CurrentIdentityDetailEnvelope `json:"body,omitempty"`
}

// NewGetCurrentIdentityOK creates GetCurrentIdentityOK with default headers values
func NewGetCurrentIdentityOK() *GetCurrentIdentityOK {

	return &GetCurrentIdentityOK{}
}

// WithPayload adds the payload to the get current identity o k response
func (o *GetCurrentIdentityOK) WithPayload(payload *rest_model.CurrentIdentityDetailEnvelope) *GetCurrentIdentityOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current identity o k response
func (o *GetCurrentIdentityOK) SetPayload(payload *rest_model.CurrentIdentityDetailEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentIdentityOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCurrentIdentityUnauthorizedCode is the HTTP code returned for type GetCurrentIdentityUnauthorized
const GetCurrentIdentityUnauthorizedCode int = 401

/*GetCurrentIdentityUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response getCurrentIdentityUnauthorized
*/
type GetCurrentIdentityUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewGetCurrentIdentityUnauthorized creates GetCurrentIdentityUnauthorized with default headers values
func NewGetCurrentIdentityUnauthorized() *GetCurrentIdentityUnauthorized {

	return &GetCurrentIdentityUnauthorized{}
}

// WithPayload adds the payload to the get current identity unauthorized response
func (o *GetCurrentIdentityUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *GetCurrentIdentityUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current identity unauthorized response
func (o *GetCurrentIdentityUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentIdentityUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
