run:
  build-tags:
    - apitests
  # Default: 1m
  timeout: 8m

# golangci gives false positives for implementations of methods using generics in generic interfaces
issues:
  exclude-rules:
    - path: 'controller/model/.*.go'
      linters:
        - unused
    - path: 'ziti/cmd/edge/verify_ca.go'
      linters:
        - staticcheck
