// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package service_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openziti/edge/rest_model"
)

// DeleteServicePolicyOKCode is the HTTP code returned for type DeleteServicePolicyOK
const DeleteServicePolicyOKCode int = 200

/*DeleteServicePolicyOK The delete request was successful and the resource has been removed

swagger:response deleteServicePolicyOK
*/
type DeleteServicePolicyOK struct {

	/*
	  In: Body
	*/
	Payload *rest_model.Empty `json:"body,omitempty"`
}

// NewDeleteServicePolicyOK creates DeleteServicePolicyOK with default headers values
func NewDeleteServicePolicyOK() *DeleteServicePolicyOK {

	return &DeleteServicePolicyOK{}
}

// WithPayload adds the payload to the delete service policy o k response
func (o *DeleteServicePolicyOK) WithPayload(payload *rest_model.Empty) *DeleteServicePolicyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete service policy o k response
func (o *DeleteServicePolicyOK) SetPayload(payload *rest_model.Empty) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServicePolicyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteServicePolicyBadRequestCode is the HTTP code returned for type DeleteServicePolicyBadRequest
const DeleteServicePolicyBadRequestCode int = 400

/*DeleteServicePolicyBadRequest The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information

swagger:response deleteServicePolicyBadRequest
*/
type DeleteServicePolicyBadRequest struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewDeleteServicePolicyBadRequest creates DeleteServicePolicyBadRequest with default headers values
func NewDeleteServicePolicyBadRequest() *DeleteServicePolicyBadRequest {

	return &DeleteServicePolicyBadRequest{}
}

// WithPayload adds the payload to the delete service policy bad request response
func (o *DeleteServicePolicyBadRequest) WithPayload(payload *rest_model.APIErrorEnvelope) *DeleteServicePolicyBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete service policy bad request response
func (o *DeleteServicePolicyBadRequest) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServicePolicyBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteServicePolicyUnauthorizedCode is the HTTP code returned for type DeleteServicePolicyUnauthorized
const DeleteServicePolicyUnauthorizedCode int = 401

/*DeleteServicePolicyUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response deleteServicePolicyUnauthorized
*/
type DeleteServicePolicyUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewDeleteServicePolicyUnauthorized creates DeleteServicePolicyUnauthorized with default headers values
func NewDeleteServicePolicyUnauthorized() *DeleteServicePolicyUnauthorized {

	return &DeleteServicePolicyUnauthorized{}
}

// WithPayload adds the payload to the delete service policy unauthorized response
func (o *DeleteServicePolicyUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *DeleteServicePolicyUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete service policy unauthorized response
func (o *DeleteServicePolicyUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServicePolicyUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteServicePolicyConflictCode is the HTTP code returned for type DeleteServicePolicyConflict
const DeleteServicePolicyConflictCode int = 409

/*DeleteServicePolicyConflict The resource requested to be removed/altered cannot be as it is referenced by another object.

swagger:response deleteServicePolicyConflict
*/
type DeleteServicePolicyConflict struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewDeleteServicePolicyConflict creates DeleteServicePolicyConflict with default headers values
func NewDeleteServicePolicyConflict() *DeleteServicePolicyConflict {

	return &DeleteServicePolicyConflict{}
}

// WithPayload adds the payload to the delete service policy conflict response
func (o *DeleteServicePolicyConflict) WithPayload(payload *rest_model.APIErrorEnvelope) *DeleteServicePolicyConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete service policy conflict response
func (o *DeleteServicePolicyConflict) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServicePolicyConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
