// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package role_attributes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openziti/edge/rest_model"
)

// ListServiceRoleAttributesOKCode is the HTTP code returned for type ListServiceRoleAttributesOK
const ListServiceRoleAttributesOKCode int = 200

/*ListServiceRoleAttributesOK A list of role attributes

swagger:response listServiceRoleAttributesOK
*/
type ListServiceRoleAttributesOK struct {

	/*
	  In: Body
	*/
	Payload *rest_model.ListRoleAttributesEnvelope `json:"body,omitempty"`
}

// NewListServiceRoleAttributesOK creates ListServiceRoleAttributesOK with default headers values
func NewListServiceRoleAttributesOK() *ListServiceRoleAttributesOK {

	return &ListServiceRoleAttributesOK{}
}

// WithPayload adds the payload to the list service role attributes o k response
func (o *ListServiceRoleAttributesOK) WithPayload(payload *rest_model.ListRoleAttributesEnvelope) *ListServiceRoleAttributesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service role attributes o k response
func (o *ListServiceRoleAttributesOK) SetPayload(payload *rest_model.ListRoleAttributesEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServiceRoleAttributesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListServiceRoleAttributesBadRequestCode is the HTTP code returned for type ListServiceRoleAttributesBadRequest
const ListServiceRoleAttributesBadRequestCode int = 400

/*ListServiceRoleAttributesBadRequest The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information

swagger:response listServiceRoleAttributesBadRequest
*/
type ListServiceRoleAttributesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListServiceRoleAttributesBadRequest creates ListServiceRoleAttributesBadRequest with default headers values
func NewListServiceRoleAttributesBadRequest() *ListServiceRoleAttributesBadRequest {

	return &ListServiceRoleAttributesBadRequest{}
}

// WithPayload adds the payload to the list service role attributes bad request response
func (o *ListServiceRoleAttributesBadRequest) WithPayload(payload *rest_model.APIErrorEnvelope) *ListServiceRoleAttributesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service role attributes bad request response
func (o *ListServiceRoleAttributesBadRequest) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServiceRoleAttributesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListServiceRoleAttributesUnauthorizedCode is the HTTP code returned for type ListServiceRoleAttributesUnauthorized
const ListServiceRoleAttributesUnauthorizedCode int = 401

/*ListServiceRoleAttributesUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response listServiceRoleAttributesUnauthorized
*/
type ListServiceRoleAttributesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListServiceRoleAttributesUnauthorized creates ListServiceRoleAttributesUnauthorized with default headers values
func NewListServiceRoleAttributesUnauthorized() *ListServiceRoleAttributesUnauthorized {

	return &ListServiceRoleAttributesUnauthorized{}
}

// WithPayload adds the payload to the list service role attributes unauthorized response
func (o *ListServiceRoleAttributesUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *ListServiceRoleAttributesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service role attributes unauthorized response
func (o *ListServiceRoleAttributesUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServiceRoleAttributesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
