// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package current_identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openziti/edge/rest_model"
)

// EnrollMfaReader is a Reader for the EnrollMfa structure.
type EnrollMfaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EnrollMfaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewEnrollMfaCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewEnrollMfaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewEnrollMfaConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEnrollMfaCreated creates a EnrollMfaCreated with default headers values
func NewEnrollMfaCreated() *EnrollMfaCreated {
	return &EnrollMfaCreated{}
}

/* EnrollMfaCreated describes a response with status code 201, with default header values.

The create request was successful and the resource has been added at the following location
*/
type EnrollMfaCreated struct {
	Payload *rest_model.CreateEnvelope
}

func (o *EnrollMfaCreated) Error() string {
	return fmt.Sprintf("[POST /current-identity/mfa][%d] enrollMfaCreated  %+v", 201, o.Payload)
}
func (o *EnrollMfaCreated) GetPayload() *rest_model.CreateEnvelope {
	return o.Payload
}

func (o *EnrollMfaCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.CreateEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnrollMfaUnauthorized creates a EnrollMfaUnauthorized with default headers values
func NewEnrollMfaUnauthorized() *EnrollMfaUnauthorized {
	return &EnrollMfaUnauthorized{}
}

/* EnrollMfaUnauthorized describes a response with status code 401, with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type EnrollMfaUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *EnrollMfaUnauthorized) Error() string {
	return fmt.Sprintf("[POST /current-identity/mfa][%d] enrollMfaUnauthorized  %+v", 401, o.Payload)
}
func (o *EnrollMfaUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *EnrollMfaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnrollMfaConflict creates a EnrollMfaConflict with default headers values
func NewEnrollMfaConflict() *EnrollMfaConflict {
	return &EnrollMfaConflict{}
}

/* EnrollMfaConflict describes a response with status code 409, with default header values.

The identity is already enrolled in MFA
*/
type EnrollMfaConflict struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *EnrollMfaConflict) Error() string {
	return fmt.Sprintf("[POST /current-identity/mfa][%d] enrollMfaConflict  %+v", 409, o.Payload)
}
func (o *EnrollMfaConflict) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *EnrollMfaConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
