// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package external_j_w_t_signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openziti/edge/rest_model"
)

// CreateExternalJwtSignerReader is a Reader for the CreateExternalJwtSigner structure.
type CreateExternalJwtSignerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateExternalJwtSignerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateExternalJwtSignerCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateExternalJwtSignerBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateExternalJwtSignerUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateExternalJwtSignerCreated creates a CreateExternalJwtSignerCreated with default headers values
func NewCreateExternalJwtSignerCreated() *CreateExternalJwtSignerCreated {
	return &CreateExternalJwtSignerCreated{}
}

/* CreateExternalJwtSignerCreated describes a response with status code 201, with default header values.

The create request was successful and the resource has been added at the following location
*/
type CreateExternalJwtSignerCreated struct {
	Payload *rest_model.CreateEnvelope
}

func (o *CreateExternalJwtSignerCreated) Error() string {
	return fmt.Sprintf("[POST /external-jwt-signers][%d] createExternalJwtSignerCreated  %+v", 201, o.Payload)
}
func (o *CreateExternalJwtSignerCreated) GetPayload() *rest_model.CreateEnvelope {
	return o.Payload
}

func (o *CreateExternalJwtSignerCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.CreateEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateExternalJwtSignerBadRequest creates a CreateExternalJwtSignerBadRequest with default headers values
func NewCreateExternalJwtSignerBadRequest() *CreateExternalJwtSignerBadRequest {
	return &CreateExternalJwtSignerBadRequest{}
}

/* CreateExternalJwtSignerBadRequest describes a response with status code 400, with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type CreateExternalJwtSignerBadRequest struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *CreateExternalJwtSignerBadRequest) Error() string {
	return fmt.Sprintf("[POST /external-jwt-signers][%d] createExternalJwtSignerBadRequest  %+v", 400, o.Payload)
}
func (o *CreateExternalJwtSignerBadRequest) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *CreateExternalJwtSignerBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateExternalJwtSignerUnauthorized creates a CreateExternalJwtSignerUnauthorized with default headers values
func NewCreateExternalJwtSignerUnauthorized() *CreateExternalJwtSignerUnauthorized {
	return &CreateExternalJwtSignerUnauthorized{}
}

/* CreateExternalJwtSignerUnauthorized describes a response with status code 401, with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type CreateExternalJwtSignerUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *CreateExternalJwtSignerUnauthorized) Error() string {
	return fmt.Sprintf("[POST /external-jwt-signers][%d] createExternalJwtSignerUnauthorized  %+v", 401, o.Payload)
}
func (o *CreateExternalJwtSignerUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *CreateExternalJwtSignerUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
