// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package edge_router_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openziti/edge/rest_model"
)

// ListEdgeRouterPolicyIdentitiesOKCode is the HTTP code returned for type ListEdgeRouterPolicyIdentitiesOK
const ListEdgeRouterPolicyIdentitiesOKCode int = 200

/*ListEdgeRouterPolicyIdentitiesOK A list of identities

swagger:response listEdgeRouterPolicyIdentitiesOK
*/
type ListEdgeRouterPolicyIdentitiesOK struct {

	/*
	  In: Body
	*/
	Payload *rest_model.ListIdentitiesEnvelope `json:"body,omitempty"`
}

// NewListEdgeRouterPolicyIdentitiesOK creates ListEdgeRouterPolicyIdentitiesOK with default headers values
func NewListEdgeRouterPolicyIdentitiesOK() *ListEdgeRouterPolicyIdentitiesOK {

	return &ListEdgeRouterPolicyIdentitiesOK{}
}

// WithPayload adds the payload to the list edge router policy identities o k response
func (o *ListEdgeRouterPolicyIdentitiesOK) WithPayload(payload *rest_model.ListIdentitiesEnvelope) *ListEdgeRouterPolicyIdentitiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge router policy identities o k response
func (o *ListEdgeRouterPolicyIdentitiesOK) SetPayload(payload *rest_model.ListIdentitiesEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRouterPolicyIdentitiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEdgeRouterPolicyIdentitiesUnauthorizedCode is the HTTP code returned for type ListEdgeRouterPolicyIdentitiesUnauthorized
const ListEdgeRouterPolicyIdentitiesUnauthorizedCode int = 401

/*ListEdgeRouterPolicyIdentitiesUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response listEdgeRouterPolicyIdentitiesUnauthorized
*/
type ListEdgeRouterPolicyIdentitiesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEdgeRouterPolicyIdentitiesUnauthorized creates ListEdgeRouterPolicyIdentitiesUnauthorized with default headers values
func NewListEdgeRouterPolicyIdentitiesUnauthorized() *ListEdgeRouterPolicyIdentitiesUnauthorized {

	return &ListEdgeRouterPolicyIdentitiesUnauthorized{}
}

// WithPayload adds the payload to the list edge router policy identities unauthorized response
func (o *ListEdgeRouterPolicyIdentitiesUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *ListEdgeRouterPolicyIdentitiesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge router policy identities unauthorized response
func (o *ListEdgeRouterPolicyIdentitiesUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRouterPolicyIdentitiesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEdgeRouterPolicyIdentitiesNotFoundCode is the HTTP code returned for type ListEdgeRouterPolicyIdentitiesNotFound
const ListEdgeRouterPolicyIdentitiesNotFoundCode int = 404

/*ListEdgeRouterPolicyIdentitiesNotFound The requested resource does not exist

swagger:response listEdgeRouterPolicyIdentitiesNotFound
*/
type ListEdgeRouterPolicyIdentitiesNotFound struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEdgeRouterPolicyIdentitiesNotFound creates ListEdgeRouterPolicyIdentitiesNotFound with default headers values
func NewListEdgeRouterPolicyIdentitiesNotFound() *ListEdgeRouterPolicyIdentitiesNotFound {

	return &ListEdgeRouterPolicyIdentitiesNotFound{}
}

// WithPayload adds the payload to the list edge router policy identities not found response
func (o *ListEdgeRouterPolicyIdentitiesNotFound) WithPayload(payload *rest_model.APIErrorEnvelope) *ListEdgeRouterPolicyIdentitiesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge router policy identities not found response
func (o *ListEdgeRouterPolicyIdentitiesNotFound) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRouterPolicyIdentitiesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
