// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package posture_checks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openziti/edge/rest_model"
)

// DetailPostureCheckReader is a Reader for the DetailPostureCheck structure.
type DetailPostureCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DetailPostureCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDetailPostureCheckOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDetailPostureCheckUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDetailPostureCheckNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDetailPostureCheckOK creates a DetailPostureCheckOK with default headers values
func NewDetailPostureCheckOK() *DetailPostureCheckOK {
	return &DetailPostureCheckOK{}
}

/* DetailPostureCheckOK describes a response with status code 200, with default header values.

Retrieves a singular posture check by id
*/
type DetailPostureCheckOK struct {
	Payload *rest_model.DetailPostureCheckEnvelope
}

func (o *DetailPostureCheckOK) Error() string {
	return fmt.Sprintf("[GET /posture-checks/{id}][%d] detailPostureCheckOK  %+v", 200, o.Payload)
}
func (o *DetailPostureCheckOK) GetPayload() *rest_model.DetailPostureCheckEnvelope {
	return o.Payload
}

func (o *DetailPostureCheckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.DetailPostureCheckEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailPostureCheckUnauthorized creates a DetailPostureCheckUnauthorized with default headers values
func NewDetailPostureCheckUnauthorized() *DetailPostureCheckUnauthorized {
	return &DetailPostureCheckUnauthorized{}
}

/* DetailPostureCheckUnauthorized describes a response with status code 401, with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type DetailPostureCheckUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *DetailPostureCheckUnauthorized) Error() string {
	return fmt.Sprintf("[GET /posture-checks/{id}][%d] detailPostureCheckUnauthorized  %+v", 401, o.Payload)
}
func (o *DetailPostureCheckUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *DetailPostureCheckUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailPostureCheckNotFound creates a DetailPostureCheckNotFound with default headers values
func NewDetailPostureCheckNotFound() *DetailPostureCheckNotFound {
	return &DetailPostureCheckNotFound{}
}

/* DetailPostureCheckNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type DetailPostureCheckNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *DetailPostureCheckNotFound) Error() string {
	return fmt.Sprintf("[GET /posture-checks/{id}][%d] detailPostureCheckNotFound  %+v", 404, o.Payload)
}
func (o *DetailPostureCheckNotFound) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *DetailPostureCheckNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
