// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package certificate_authority

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openziti/edge/rest_model"
)

// GetCaJWTReader is a Reader for the GetCaJWT structure.
type GetCaJWTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCaJWTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCaJWTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCaJWTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCaJWTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCaJWTOK creates a GetCaJWTOK with default headers values
func NewGetCaJWTOK() *GetCaJWTOK {
	return &GetCaJWTOK{}
}

/* GetCaJWTOK describes a response with status code 200, with default header values.

The result is the JWT text to validate the CA
*/
type GetCaJWTOK struct {
	Payload string
}

func (o *GetCaJWTOK) Error() string {
	return fmt.Sprintf("[GET /cas/{id}/jwt][%d] getCaJwtOK  %+v", 200, o.Payload)
}
func (o *GetCaJWTOK) GetPayload() string {
	return o.Payload
}

func (o *GetCaJWTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCaJWTUnauthorized creates a GetCaJWTUnauthorized with default headers values
func NewGetCaJWTUnauthorized() *GetCaJWTUnauthorized {
	return &GetCaJWTUnauthorized{}
}

/* GetCaJWTUnauthorized describes a response with status code 401, with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type GetCaJWTUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *GetCaJWTUnauthorized) Error() string {
	return fmt.Sprintf("[GET /cas/{id}/jwt][%d] getCaJwtUnauthorized  %+v", 401, o.Payload)
}
func (o *GetCaJWTUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *GetCaJWTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCaJWTNotFound creates a GetCaJWTNotFound with default headers values
func NewGetCaJWTNotFound() *GetCaJWTNotFound {
	return &GetCaJWTNotFound{}
}

/* GetCaJWTNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type GetCaJWTNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *GetCaJWTNotFound) Error() string {
	return fmt.Sprintf("[GET /cas/{id}/jwt][%d] getCaJwtNotFound  %+v", 404, o.Payload)
}
func (o *GetCaJWTNotFound) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *GetCaJWTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
