// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openziti/edge/rest_model"
)

// DetailSessionRoutePathReader is a Reader for the DetailSessionRoutePath structure.
type DetailSessionRoutePathReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DetailSessionRoutePathReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDetailSessionRoutePathOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDetailSessionRoutePathUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDetailSessionRoutePathNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDetailSessionRoutePathOK creates a DetailSessionRoutePathOK with default headers values
func NewDetailSessionRoutePathOK() *DetailSessionRoutePathOK {
	return &DetailSessionRoutePathOK{}
}

/* DetailSessionRoutePathOK describes a response with status code 200, with default header values.

A single session's route path
*/
type DetailSessionRoutePathOK struct {
	Payload *rest_model.DetailSessionRoutePathEnvelope
}

func (o *DetailSessionRoutePathOK) Error() string {
	return fmt.Sprintf("[GET /sessions/{id}/route-path][%d] detailSessionRoutePathOK  %+v", 200, o.Payload)
}
func (o *DetailSessionRoutePathOK) GetPayload() *rest_model.DetailSessionRoutePathEnvelope {
	return o.Payload
}

func (o *DetailSessionRoutePathOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.DetailSessionRoutePathEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailSessionRoutePathUnauthorized creates a DetailSessionRoutePathUnauthorized with default headers values
func NewDetailSessionRoutePathUnauthorized() *DetailSessionRoutePathUnauthorized {
	return &DetailSessionRoutePathUnauthorized{}
}

/* DetailSessionRoutePathUnauthorized describes a response with status code 401, with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type DetailSessionRoutePathUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *DetailSessionRoutePathUnauthorized) Error() string {
	return fmt.Sprintf("[GET /sessions/{id}/route-path][%d] detailSessionRoutePathUnauthorized  %+v", 401, o.Payload)
}
func (o *DetailSessionRoutePathUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *DetailSessionRoutePathUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailSessionRoutePathNotFound creates a DetailSessionRoutePathNotFound with default headers values
func NewDetailSessionRoutePathNotFound() *DetailSessionRoutePathNotFound {
	return &DetailSessionRoutePathNotFound{}
}

/* DetailSessionRoutePathNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type DetailSessionRoutePathNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *DetailSessionRoutePathNotFound) Error() string {
	return fmt.Sprintf("[GET /sessions/{id}/route-path][%d] detailSessionRoutePathNotFound  %+v", 404, o.Payload)
}
func (o *DetailSessionRoutePathNotFound) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *DetailSessionRoutePathNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
