// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package current_identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/openziti/edge/rest_model"
)

// NewCreateMfaRecoveryCodesParams creates a new CreateMfaRecoveryCodesParams object
// with the default values initialized.
func NewCreateMfaRecoveryCodesParams() *CreateMfaRecoveryCodesParams {
	var ()
	return &CreateMfaRecoveryCodesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateMfaRecoveryCodesParamsWithTimeout creates a new CreateMfaRecoveryCodesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateMfaRecoveryCodesParamsWithTimeout(timeout time.Duration) *CreateMfaRecoveryCodesParams {
	var ()
	return &CreateMfaRecoveryCodesParams{

		timeout: timeout,
	}
}

// NewCreateMfaRecoveryCodesParamsWithContext creates a new CreateMfaRecoveryCodesParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateMfaRecoveryCodesParamsWithContext(ctx context.Context) *CreateMfaRecoveryCodesParams {
	var ()
	return &CreateMfaRecoveryCodesParams{

		Context: ctx,
	}
}

// NewCreateMfaRecoveryCodesParamsWithHTTPClient creates a new CreateMfaRecoveryCodesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateMfaRecoveryCodesParamsWithHTTPClient(client *http.Client) *CreateMfaRecoveryCodesParams {
	var ()
	return &CreateMfaRecoveryCodesParams{
		HTTPClient: client,
	}
}

/*CreateMfaRecoveryCodesParams contains all the parameters to send to the API endpoint
for the create mfa recovery codes operation typically these are written to a http.Request
*/
type CreateMfaRecoveryCodesParams struct {

	/*MfaCode
	  An MFA validation request

	*/
	MfaCode *rest_model.MfaCode

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create mfa recovery codes params
func (o *CreateMfaRecoveryCodesParams) WithTimeout(timeout time.Duration) *CreateMfaRecoveryCodesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create mfa recovery codes params
func (o *CreateMfaRecoveryCodesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create mfa recovery codes params
func (o *CreateMfaRecoveryCodesParams) WithContext(ctx context.Context) *CreateMfaRecoveryCodesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create mfa recovery codes params
func (o *CreateMfaRecoveryCodesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create mfa recovery codes params
func (o *CreateMfaRecoveryCodesParams) WithHTTPClient(client *http.Client) *CreateMfaRecoveryCodesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create mfa recovery codes params
func (o *CreateMfaRecoveryCodesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMfaCode adds the mfaCode to the create mfa recovery codes params
func (o *CreateMfaRecoveryCodesParams) WithMfaCode(mfaCode *rest_model.MfaCode) *CreateMfaRecoveryCodesParams {
	o.SetMfaCode(mfaCode)
	return o
}

// SetMfaCode adds the mfaCode to the create mfa recovery codes params
func (o *CreateMfaRecoveryCodesParams) SetMfaCode(mfaCode *rest_model.MfaCode) {
	o.MfaCode = mfaCode
}

// WriteToRequest writes these params to a swagger request
func (o *CreateMfaRecoveryCodesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.MfaCode != nil {
		if err := r.SetBodyParam(o.MfaCode); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
