// Code generated by protoc-gen-go. DO NOT EDIT.
// source: edge_ctrl.proto

package edge_ctrl_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContentType int32

const (
	ContentType_Zero            ContentType = 0
	ContentType_ServerHelloType ContentType = 20000
	ContentType_ClientHelloType ContentType = 20001
	ContentType_ErrorType       ContentType = 20002
	// SessionAddedType = 20100;
	// SessionUpdatedType = 20101;
	ContentType_SessionRemovedType                      ContentType = 20102
	ContentType_ApiSessionAddedType                     ContentType = 20200
	ContentType_ApiSessionUpdatedType                   ContentType = 20201
	ContentType_ApiSessionRemovedType                   ContentType = 20202
	ContentType_ApiSessionHeartbeatType                 ContentType = 20203
	ContentType_RequestClientReSyncType                 ContentType = 20204
	ContentType_CreateCircuitRequestType                ContentType = 20205
	ContentType_CreateCircuitResponseType               ContentType = 20206
	ContentType_CreateTerminatorRequestType             ContentType = 20207
	ContentType_CreateTerminatorResponseType            ContentType = 20208
	ContentType_UpdateTerminatorRequestType             ContentType = 20209
	ContentType_UpdateTerminatorResponseType            ContentType = 20210
	ContentType_RemoveTerminatorRequestType             ContentType = 20211
	ContentType_RemoveTerminatorResponseType            ContentType = 20212
	ContentType_ValidateSessionsRequestType             ContentType = 20213
	ContentType_HealthEventType                         ContentType = 20214
	ContentType_EnrollType                              ContentType = 20300
	ContentType_EnrollmentCertsResponseType             ContentType = 20301
	ContentType_EnrollmentExtendRouterRequestType       ContentType = 20302
	ContentType_EnrollmentExtendRouterVerifyRequestType ContentType = 20303
	ContentType_CreateApiSessionRequestType             ContentType = 20400
	ContentType_CreateApiSessionResponseType            ContentType = 20401
	ContentType_CreateCircuitForServiceRequestType      ContentType = 20402
	ContentType_CreateCircuitForServiceResponseType     ContentType = 20403
	ContentType_ListServicesRequestType                 ContentType = 20404
	ContentType_ServiceListType                         ContentType = 20405
	ContentType_CreateTunnelTerminatorRequestType       ContentType = 20406
	ContentType_CreateTunnelTerminatorResponseType      ContentType = 20407
	ContentType_UpdateTunnelTerminatorRequestType       ContentType = 20408
	ContentType_UpdateTunnelTerminatorResponseType      ContentType = 20409
	ContentType_RemoveTunnelTerminatorRequestType       ContentType = 20410
	ContentType_RemoveTunnelTerminatorResponseType      ContentType = 20411
	ContentType_TunnelHealthEventType                   ContentType = 20412
)

var ContentType_name = map[int32]string{
	0:     "Zero",
	20000: "ServerHelloType",
	20001: "ClientHelloType",
	20002: "ErrorType",
	20102: "SessionRemovedType",
	20200: "ApiSessionAddedType",
	20201: "ApiSessionUpdatedType",
	20202: "ApiSessionRemovedType",
	20203: "ApiSessionHeartbeatType",
	20204: "RequestClientReSyncType",
	20205: "CreateCircuitRequestType",
	20206: "CreateCircuitResponseType",
	20207: "CreateTerminatorRequestType",
	20208: "CreateTerminatorResponseType",
	20209: "UpdateTerminatorRequestType",
	20210: "UpdateTerminatorResponseType",
	20211: "RemoveTerminatorRequestType",
	20212: "RemoveTerminatorResponseType",
	20213: "ValidateSessionsRequestType",
	20214: "HealthEventType",
	20300: "EnrollType",
	20301: "EnrollmentCertsResponseType",
	20302: "EnrollmentExtendRouterRequestType",
	20303: "EnrollmentExtendRouterVerifyRequestType",
	20400: "CreateApiSessionRequestType",
	20401: "CreateApiSessionResponseType",
	20402: "CreateCircuitForServiceRequestType",
	20403: "CreateCircuitForServiceResponseType",
	20404: "ListServicesRequestType",
	20405: "ServiceListType",
	20406: "CreateTunnelTerminatorRequestType",
	20407: "CreateTunnelTerminatorResponseType",
	20408: "UpdateTunnelTerminatorRequestType",
	20409: "UpdateTunnelTerminatorResponseType",
	20410: "RemoveTunnelTerminatorRequestType",
	20411: "RemoveTunnelTerminatorResponseType",
	20412: "TunnelHealthEventType",
}

var ContentType_value = map[string]int32{
	"Zero":                                    0,
	"ServerHelloType":                         20000,
	"ClientHelloType":                         20001,
	"ErrorType":                               20002,
	"SessionRemovedType":                      20102,
	"ApiSessionAddedType":                     20200,
	"ApiSessionUpdatedType":                   20201,
	"ApiSessionRemovedType":                   20202,
	"ApiSessionHeartbeatType":                 20203,
	"RequestClientReSyncType":                 20204,
	"CreateCircuitRequestType":                20205,
	"CreateCircuitResponseType":               20206,
	"CreateTerminatorRequestType":             20207,
	"CreateTerminatorResponseType":            20208,
	"UpdateTerminatorRequestType":             20209,
	"UpdateTerminatorResponseType":            20210,
	"RemoveTerminatorRequestType":             20211,
	"RemoveTerminatorResponseType":            20212,
	"ValidateSessionsRequestType":             20213,
	"HealthEventType":                         20214,
	"EnrollType":                              20300,
	"EnrollmentCertsResponseType":             20301,
	"EnrollmentExtendRouterRequestType":       20302,
	"EnrollmentExtendRouterVerifyRequestType": 20303,
	"CreateApiSessionRequestType":             20400,
	"CreateApiSessionResponseType":            20401,
	"CreateCircuitForServiceRequestType":      20402,
	"CreateCircuitForServiceResponseType":     20403,
	"ListServicesRequestType":                 20404,
	"ServiceListType":                         20405,
	"CreateTunnelTerminatorRequestType":       20406,
	"CreateTunnelTerminatorResponseType":      20407,
	"UpdateTunnelTerminatorRequestType":       20408,
	"UpdateTunnelTerminatorResponseType":      20409,
	"RemoveTunnelTerminatorRequestType":       20410,
	"RemoveTunnelTerminatorResponseType":      20411,
	"TunnelHealthEventType":                   20412,
}

func (x ContentType) String() string {
	return proto.EnumName(ContentType_name, int32(x))
}

func (ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{0}
}

type SessionType int32

const (
	SessionType_Dial SessionType = 0
	SessionType_Bind SessionType = 1
)

var SessionType_name = map[int32]string{
	0: "Dial",
	1: "Bind",
}

var SessionType_value = map[string]int32{
	"Dial": 0,
	"Bind": 1,
}

func (x SessionType) String() string {
	return proto.EnumName(SessionType_name, int32(x))
}

func (SessionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{1}
}

type Header int32

const (
	Header_HeaderZero   Header = 0
	Header_TerminatorId Header = 1022
	Header_CheckPassed  Header = 1023
)

var Header_name = map[int32]string{
	0:    "HeaderZero",
	1022: "TerminatorId",
	1023: "CheckPassed",
}

var Header_value = map[string]int32{
	"HeaderZero":   0,
	"TerminatorId": 1022,
	"CheckPassed":  1023,
}

func (x Header) String() string {
	return proto.EnumName(Header_name, int32(x))
}

func (Header) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{2}
}

type TerminatorPrecedence int32

const (
	TerminatorPrecedence_Default  TerminatorPrecedence = 0
	TerminatorPrecedence_Required TerminatorPrecedence = 1
	TerminatorPrecedence_Failed   TerminatorPrecedence = 2
)

var TerminatorPrecedence_name = map[int32]string{
	0: "Default",
	1: "Required",
	2: "Failed",
}

var TerminatorPrecedence_value = map[string]int32{
	"Default":  0,
	"Required": 1,
	"Failed":   2,
}

func (x TerminatorPrecedence) String() string {
	return proto.EnumName(TerminatorPrecedence_name, int32(x))
}

func (TerminatorPrecedence) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{3}
}

type ServerHello struct {
	Version              string            `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Data                 map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ServerHello) Reset()         { *m = ServerHello{} }
func (m *ServerHello) String() string { return proto.CompactTextString(m) }
func (*ServerHello) ProtoMessage()    {}
func (*ServerHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{0}
}

func (m *ServerHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerHello.Unmarshal(m, b)
}
func (m *ServerHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerHello.Marshal(b, m, deterministic)
}
func (m *ServerHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerHello.Merge(m, src)
}
func (m *ServerHello) XXX_Size() int {
	return xxx_messageInfo_ServerHello.Size(m)
}
func (m *ServerHello) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerHello.DiscardUnknown(m)
}

var xxx_messageInfo_ServerHello proto.InternalMessageInfo

func (m *ServerHello) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServerHello) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type ClientHello struct {
	Version              string            `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Hostname             string            `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Protocols            []string          `protobuf:"bytes,3,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Data                 map[string]string `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ProtocolPorts        []string          `protobuf:"bytes,5,rep,name=protocolPorts,proto3" json:"protocolPorts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClientHello) Reset()         { *m = ClientHello{} }
func (m *ClientHello) String() string { return proto.CompactTextString(m) }
func (*ClientHello) ProtoMessage()    {}
func (*ClientHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{1}
}

func (m *ClientHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientHello.Unmarshal(m, b)
}
func (m *ClientHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientHello.Marshal(b, m, deterministic)
}
func (m *ClientHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientHello.Merge(m, src)
}
func (m *ClientHello) XXX_Size() int {
	return xxx_messageInfo_ClientHello.Size(m)
}
func (m *ClientHello) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientHello.DiscardUnknown(m)
}

var xxx_messageInfo_ClientHello proto.InternalMessageInfo

func (m *ClientHello) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ClientHello) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *ClientHello) GetProtocols() []string {
	if m != nil {
		return m.Protocols
	}
	return nil
}

func (m *ClientHello) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ClientHello) GetProtocolPorts() []string {
	if m != nil {
		return m.ProtocolPorts
	}
	return nil
}

type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Cause                string   `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

type Service struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EncryptionRequired   bool     `protobuf:"varint,3,opt,name=encryptionRequired,proto3" json:"encryptionRequired,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{3}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetEncryptionRequired() bool {
	if m != nil {
		return m.EncryptionRequired
	}
	return false
}

type Session struct {
	Token                string      `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Type                 SessionType `protobuf:"varint,2,opt,name=type,proto3,enum=ziti.edge_ctrl.pb.SessionType" json:"type,omitempty"`
	CertFingerprints     []string    `protobuf:"bytes,3,rep,name=certFingerprints,proto3" json:"certFingerprints,omitempty"`
	Urls                 []string    `protobuf:"bytes,4,rep,name=urls,proto3" json:"urls,omitempty"`
	Service              *Service    `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	Id                   string      `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	ApiSessionId         string      `protobuf:"bytes,8,opt,name=apiSessionId,proto3" json:"apiSessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{4}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Session) GetType() SessionType {
	if m != nil {
		return m.Type
	}
	return SessionType_Dial
}

func (m *Session) GetCertFingerprints() []string {
	if m != nil {
		return m.CertFingerprints
	}
	return nil
}

func (m *Session) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *Session) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetApiSessionId() string {
	if m != nil {
		return m.ApiSessionId
	}
	return ""
}

type ApiSession struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CertFingerprints     []string `protobuf:"bytes,2,rep,name=certFingerprints,proto3" json:"certFingerprints,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiSession) Reset()         { *m = ApiSession{} }
func (m *ApiSession) String() string { return proto.CompactTextString(m) }
func (*ApiSession) ProtoMessage()    {}
func (*ApiSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{5}
}

func (m *ApiSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiSession.Unmarshal(m, b)
}
func (m *ApiSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiSession.Marshal(b, m, deterministic)
}
func (m *ApiSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiSession.Merge(m, src)
}
func (m *ApiSession) XXX_Size() int {
	return xxx_messageInfo_ApiSession.Size(m)
}
func (m *ApiSession) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiSession.DiscardUnknown(m)
}

var xxx_messageInfo_ApiSession proto.InternalMessageInfo

func (m *ApiSession) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ApiSession) GetCertFingerprints() []string {
	if m != nil {
		return m.CertFingerprints
	}
	return nil
}

func (m *ApiSession) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ApiSessionAdded struct {
	IsFullState          bool          `protobuf:"varint,1,opt,name=isFullState,proto3" json:"isFullState,omitempty"`
	ApiSessions          []*ApiSession `protobuf:"bytes,2,rep,name=apiSessions,proto3" json:"apiSessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ApiSessionAdded) Reset()         { *m = ApiSessionAdded{} }
func (m *ApiSessionAdded) String() string { return proto.CompactTextString(m) }
func (*ApiSessionAdded) ProtoMessage()    {}
func (*ApiSessionAdded) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{6}
}

func (m *ApiSessionAdded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiSessionAdded.Unmarshal(m, b)
}
func (m *ApiSessionAdded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiSessionAdded.Marshal(b, m, deterministic)
}
func (m *ApiSessionAdded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiSessionAdded.Merge(m, src)
}
func (m *ApiSessionAdded) XXX_Size() int {
	return xxx_messageInfo_ApiSessionAdded.Size(m)
}
func (m *ApiSessionAdded) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiSessionAdded.DiscardUnknown(m)
}

var xxx_messageInfo_ApiSessionAdded proto.InternalMessageInfo

func (m *ApiSessionAdded) GetIsFullState() bool {
	if m != nil {
		return m.IsFullState
	}
	return false
}

func (m *ApiSessionAdded) GetApiSessions() []*ApiSession {
	if m != nil {
		return m.ApiSessions
	}
	return nil
}

type ApiSessionUpdated struct {
	ApiSessions          []*ApiSession `protobuf:"bytes,1,rep,name=apiSessions,proto3" json:"apiSessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ApiSessionUpdated) Reset()         { *m = ApiSessionUpdated{} }
func (m *ApiSessionUpdated) String() string { return proto.CompactTextString(m) }
func (*ApiSessionUpdated) ProtoMessage()    {}
func (*ApiSessionUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{7}
}

func (m *ApiSessionUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiSessionUpdated.Unmarshal(m, b)
}
func (m *ApiSessionUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiSessionUpdated.Marshal(b, m, deterministic)
}
func (m *ApiSessionUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiSessionUpdated.Merge(m, src)
}
func (m *ApiSessionUpdated) XXX_Size() int {
	return xxx_messageInfo_ApiSessionUpdated.Size(m)
}
func (m *ApiSessionUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiSessionUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_ApiSessionUpdated proto.InternalMessageInfo

func (m *ApiSessionUpdated) GetApiSessions() []*ApiSession {
	if m != nil {
		return m.ApiSessions
	}
	return nil
}

type ApiSessionRemoved struct {
	Tokens               []string `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Ids                  []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiSessionRemoved) Reset()         { *m = ApiSessionRemoved{} }
func (m *ApiSessionRemoved) String() string { return proto.CompactTextString(m) }
func (*ApiSessionRemoved) ProtoMessage()    {}
func (*ApiSessionRemoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{8}
}

func (m *ApiSessionRemoved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiSessionRemoved.Unmarshal(m, b)
}
func (m *ApiSessionRemoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiSessionRemoved.Marshal(b, m, deterministic)
}
func (m *ApiSessionRemoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiSessionRemoved.Merge(m, src)
}
func (m *ApiSessionRemoved) XXX_Size() int {
	return xxx_messageInfo_ApiSessionRemoved.Size(m)
}
func (m *ApiSessionRemoved) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiSessionRemoved.DiscardUnknown(m)
}

var xxx_messageInfo_ApiSessionRemoved proto.InternalMessageInfo

func (m *ApiSessionRemoved) GetTokens() []string {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *ApiSessionRemoved) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ApiSessionHeartbeat struct {
	Tokens               []string `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiSessionHeartbeat) Reset()         { *m = ApiSessionHeartbeat{} }
func (m *ApiSessionHeartbeat) String() string { return proto.CompactTextString(m) }
func (*ApiSessionHeartbeat) ProtoMessage()    {}
func (*ApiSessionHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{9}
}

func (m *ApiSessionHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiSessionHeartbeat.Unmarshal(m, b)
}
func (m *ApiSessionHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiSessionHeartbeat.Marshal(b, m, deterministic)
}
func (m *ApiSessionHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiSessionHeartbeat.Merge(m, src)
}
func (m *ApiSessionHeartbeat) XXX_Size() int {
	return xxx_messageInfo_ApiSessionHeartbeat.Size(m)
}
func (m *ApiSessionHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiSessionHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_ApiSessionHeartbeat proto.InternalMessageInfo

func (m *ApiSessionHeartbeat) GetTokens() []string {
	if m != nil {
		return m.Tokens
	}
	return nil
}

type SessionRemoved struct {
	Tokens               []string `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Ids                  []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRemoved) Reset()         { *m = SessionRemoved{} }
func (m *SessionRemoved) String() string { return proto.CompactTextString(m) }
func (*SessionRemoved) ProtoMessage()    {}
func (*SessionRemoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{10}
}

func (m *SessionRemoved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRemoved.Unmarshal(m, b)
}
func (m *SessionRemoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRemoved.Marshal(b, m, deterministic)
}
func (m *SessionRemoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRemoved.Merge(m, src)
}
func (m *SessionRemoved) XXX_Size() int {
	return xxx_messageInfo_SessionRemoved.Size(m)
}
func (m *SessionRemoved) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRemoved.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRemoved proto.InternalMessageInfo

func (m *SessionRemoved) GetTokens() []string {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *SessionRemoved) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type RequestClientReSync struct {
	Reason               string   `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestClientReSync) Reset()         { *m = RequestClientReSync{} }
func (m *RequestClientReSync) String() string { return proto.CompactTextString(m) }
func (*RequestClientReSync) ProtoMessage()    {}
func (*RequestClientReSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{11}
}

func (m *RequestClientReSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestClientReSync.Unmarshal(m, b)
}
func (m *RequestClientReSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestClientReSync.Marshal(b, m, deterministic)
}
func (m *RequestClientReSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestClientReSync.Merge(m, src)
}
func (m *RequestClientReSync) XXX_Size() int {
	return xxx_messageInfo_RequestClientReSync.Size(m)
}
func (m *RequestClientReSync) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestClientReSync.DiscardUnknown(m)
}

var xxx_messageInfo_RequestClientReSync proto.InternalMessageInfo

func (m *RequestClientReSync) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type CreateCircuitRequest struct {
	SessionToken         string            `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	Fingerprints         []string          `protobuf:"bytes,2,rep,name=fingerprints,proto3" json:"fingerprints,omitempty"`
	TerminatorIdentity   string            `protobuf:"bytes,3,opt,name=terminatorIdentity,proto3" json:"terminatorIdentity,omitempty"`
	PeerData             map[uint32][]byte `protobuf:"bytes,4,rep,name=peerData,proto3" json:"peerData,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateCircuitRequest) Reset()         { *m = CreateCircuitRequest{} }
func (m *CreateCircuitRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCircuitRequest) ProtoMessage()    {}
func (*CreateCircuitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{12}
}

func (m *CreateCircuitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCircuitRequest.Unmarshal(m, b)
}
func (m *CreateCircuitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCircuitRequest.Marshal(b, m, deterministic)
}
func (m *CreateCircuitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCircuitRequest.Merge(m, src)
}
func (m *CreateCircuitRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCircuitRequest.Size(m)
}
func (m *CreateCircuitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCircuitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCircuitRequest proto.InternalMessageInfo

func (m *CreateCircuitRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *CreateCircuitRequest) GetFingerprints() []string {
	if m != nil {
		return m.Fingerprints
	}
	return nil
}

func (m *CreateCircuitRequest) GetTerminatorIdentity() string {
	if m != nil {
		return m.TerminatorIdentity
	}
	return ""
}

func (m *CreateCircuitRequest) GetPeerData() map[uint32][]byte {
	if m != nil {
		return m.PeerData
	}
	return nil
}

type CreateCircuitResponse struct {
	CircuitId            string            `protobuf:"bytes,1,opt,name=circuitId,proto3" json:"circuitId,omitempty"`
	Address              string            `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PeerData             map[uint32][]byte `protobuf:"bytes,3,rep,name=peerData,proto3" json:"peerData,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateCircuitResponse) Reset()         { *m = CreateCircuitResponse{} }
func (m *CreateCircuitResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCircuitResponse) ProtoMessage()    {}
func (*CreateCircuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{13}
}

func (m *CreateCircuitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCircuitResponse.Unmarshal(m, b)
}
func (m *CreateCircuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCircuitResponse.Marshal(b, m, deterministic)
}
func (m *CreateCircuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCircuitResponse.Merge(m, src)
}
func (m *CreateCircuitResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCircuitResponse.Size(m)
}
func (m *CreateCircuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCircuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCircuitResponse proto.InternalMessageInfo

func (m *CreateCircuitResponse) GetCircuitId() string {
	if m != nil {
		return m.CircuitId
	}
	return ""
}

func (m *CreateCircuitResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateCircuitResponse) GetPeerData() map[uint32][]byte {
	if m != nil {
		return m.PeerData
	}
	return nil
}

type CreateTerminatorRequest struct {
	SessionToken         string               `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	Fingerprints         []string             `protobuf:"bytes,2,rep,name=fingerprints,proto3" json:"fingerprints,omitempty"`
	PeerData             map[uint32][]byte    `protobuf:"bytes,3,rep,name=peerData,proto3" json:"peerData,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cost                 uint32               `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	Precedence           TerminatorPrecedence `protobuf:"varint,5,opt,name=precedence,proto3,enum=ziti.edge_ctrl.pb.TerminatorPrecedence" json:"precedence,omitempty"`
	Identity             string               `protobuf:"bytes,6,opt,name=identity,proto3" json:"identity,omitempty"`
	IdentitySecret       []byte               `protobuf:"bytes,7,opt,name=identitySecret,proto3" json:"identitySecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateTerminatorRequest) Reset()         { *m = CreateTerminatorRequest{} }
func (m *CreateTerminatorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTerminatorRequest) ProtoMessage()    {}
func (*CreateTerminatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{14}
}

func (m *CreateTerminatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTerminatorRequest.Unmarshal(m, b)
}
func (m *CreateTerminatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTerminatorRequest.Marshal(b, m, deterministic)
}
func (m *CreateTerminatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTerminatorRequest.Merge(m, src)
}
func (m *CreateTerminatorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTerminatorRequest.Size(m)
}
func (m *CreateTerminatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTerminatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTerminatorRequest proto.InternalMessageInfo

func (m *CreateTerminatorRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *CreateTerminatorRequest) GetFingerprints() []string {
	if m != nil {
		return m.Fingerprints
	}
	return nil
}

func (m *CreateTerminatorRequest) GetPeerData() map[uint32][]byte {
	if m != nil {
		return m.PeerData
	}
	return nil
}

func (m *CreateTerminatorRequest) GetCost() uint32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *CreateTerminatorRequest) GetPrecedence() TerminatorPrecedence {
	if m != nil {
		return m.Precedence
	}
	return TerminatorPrecedence_Default
}

func (m *CreateTerminatorRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *CreateTerminatorRequest) GetIdentitySecret() []byte {
	if m != nil {
		return m.IdentitySecret
	}
	return nil
}

type RemoveTerminatorRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	Fingerprints         []string `protobuf:"bytes,2,rep,name=fingerprints,proto3" json:"fingerprints,omitempty"`
	TerminatorId         string   `protobuf:"bytes,3,opt,name=terminatorId,proto3" json:"terminatorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTerminatorRequest) Reset()         { *m = RemoveTerminatorRequest{} }
func (m *RemoveTerminatorRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTerminatorRequest) ProtoMessage()    {}
func (*RemoveTerminatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{15}
}

func (m *RemoveTerminatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTerminatorRequest.Unmarshal(m, b)
}
func (m *RemoveTerminatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTerminatorRequest.Marshal(b, m, deterministic)
}
func (m *RemoveTerminatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTerminatorRequest.Merge(m, src)
}
func (m *RemoveTerminatorRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTerminatorRequest.Size(m)
}
func (m *RemoveTerminatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTerminatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTerminatorRequest proto.InternalMessageInfo

func (m *RemoveTerminatorRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *RemoveTerminatorRequest) GetFingerprints() []string {
	if m != nil {
		return m.Fingerprints
	}
	return nil
}

func (m *RemoveTerminatorRequest) GetTerminatorId() string {
	if m != nil {
		return m.TerminatorId
	}
	return ""
}

type UpdateTerminatorRequest struct {
	SessionToken         string               `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	Fingerprints         []string             `protobuf:"bytes,2,rep,name=fingerprints,proto3" json:"fingerprints,omitempty"`
	TerminatorId         string               `protobuf:"bytes,3,opt,name=terminatorId,proto3" json:"terminatorId,omitempty"`
	Cost                 uint32               `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	Precedence           TerminatorPrecedence `protobuf:"varint,5,opt,name=precedence,proto3,enum=ziti.edge_ctrl.pb.TerminatorPrecedence" json:"precedence,omitempty"`
	UpdatePrecedence     bool                 `protobuf:"varint,6,opt,name=updatePrecedence,proto3" json:"updatePrecedence,omitempty"`
	UpdateCost           bool                 `protobuf:"varint,7,opt,name=updateCost,proto3" json:"updateCost,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateTerminatorRequest) Reset()         { *m = UpdateTerminatorRequest{} }
func (m *UpdateTerminatorRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTerminatorRequest) ProtoMessage()    {}
func (*UpdateTerminatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{16}
}

func (m *UpdateTerminatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTerminatorRequest.Unmarshal(m, b)
}
func (m *UpdateTerminatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTerminatorRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTerminatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTerminatorRequest.Merge(m, src)
}
func (m *UpdateTerminatorRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTerminatorRequest.Size(m)
}
func (m *UpdateTerminatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTerminatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTerminatorRequest proto.InternalMessageInfo

func (m *UpdateTerminatorRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *UpdateTerminatorRequest) GetFingerprints() []string {
	if m != nil {
		return m.Fingerprints
	}
	return nil
}

func (m *UpdateTerminatorRequest) GetTerminatorId() string {
	if m != nil {
		return m.TerminatorId
	}
	return ""
}

func (m *UpdateTerminatorRequest) GetCost() uint32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *UpdateTerminatorRequest) GetPrecedence() TerminatorPrecedence {
	if m != nil {
		return m.Precedence
	}
	return TerminatorPrecedence_Default
}

func (m *UpdateTerminatorRequest) GetUpdatePrecedence() bool {
	if m != nil {
		return m.UpdatePrecedence
	}
	return false
}

func (m *UpdateTerminatorRequest) GetUpdateCost() bool {
	if m != nil {
		return m.UpdateCost
	}
	return false
}

type HealthEventRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	Fingerprints         []string `protobuf:"bytes,2,rep,name=fingerprints,proto3" json:"fingerprints,omitempty"`
	TerminatorId         string   `protobuf:"bytes,3,opt,name=terminatorId,proto3" json:"terminatorId,omitempty"`
	CheckPassed          bool     `protobuf:"varint,4,opt,name=checkPassed,proto3" json:"checkPassed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthEventRequest) Reset()         { *m = HealthEventRequest{} }
func (m *HealthEventRequest) String() string { return proto.CompactTextString(m) }
func (*HealthEventRequest) ProtoMessage()    {}
func (*HealthEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{17}
}

func (m *HealthEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthEventRequest.Unmarshal(m, b)
}
func (m *HealthEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthEventRequest.Marshal(b, m, deterministic)
}
func (m *HealthEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthEventRequest.Merge(m, src)
}
func (m *HealthEventRequest) XXX_Size() int {
	return xxx_messageInfo_HealthEventRequest.Size(m)
}
func (m *HealthEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthEventRequest proto.InternalMessageInfo

func (m *HealthEventRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *HealthEventRequest) GetFingerprints() []string {
	if m != nil {
		return m.Fingerprints
	}
	return nil
}

func (m *HealthEventRequest) GetTerminatorId() string {
	if m != nil {
		return m.TerminatorId
	}
	return ""
}

func (m *HealthEventRequest) GetCheckPassed() bool {
	if m != nil {
		return m.CheckPassed
	}
	return false
}

type ValidateSessionsRequest struct {
	SessionTokens        []string `protobuf:"bytes,1,rep,name=sessionTokens,proto3" json:"sessionTokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateSessionsRequest) Reset()         { *m = ValidateSessionsRequest{} }
func (m *ValidateSessionsRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateSessionsRequest) ProtoMessage()    {}
func (*ValidateSessionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{18}
}

func (m *ValidateSessionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateSessionsRequest.Unmarshal(m, b)
}
func (m *ValidateSessionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateSessionsRequest.Marshal(b, m, deterministic)
}
func (m *ValidateSessionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateSessionsRequest.Merge(m, src)
}
func (m *ValidateSessionsRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateSessionsRequest.Size(m)
}
func (m *ValidateSessionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateSessionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateSessionsRequest proto.InternalMessageInfo

func (m *ValidateSessionsRequest) GetSessionTokens() []string {
	if m != nil {
		return m.SessionTokens
	}
	return nil
}

type EnvInfo struct {
	Arch                 string   `protobuf:"bytes,1,opt,name=arch,proto3" json:"arch,omitempty"`
	Os                   string   `protobuf:"bytes,2,opt,name=Os,proto3" json:"Os,omitempty"`
	OsRelease            string   `protobuf:"bytes,3,opt,name=OsRelease,proto3" json:"OsRelease,omitempty"`
	OsVersion            string   `protobuf:"bytes,4,opt,name=OsVersion,proto3" json:"OsVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvInfo) Reset()         { *m = EnvInfo{} }
func (m *EnvInfo) String() string { return proto.CompactTextString(m) }
func (*EnvInfo) ProtoMessage()    {}
func (*EnvInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{19}
}

func (m *EnvInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvInfo.Unmarshal(m, b)
}
func (m *EnvInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvInfo.Marshal(b, m, deterministic)
}
func (m *EnvInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvInfo.Merge(m, src)
}
func (m *EnvInfo) XXX_Size() int {
	return xxx_messageInfo_EnvInfo.Size(m)
}
func (m *EnvInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EnvInfo proto.InternalMessageInfo

func (m *EnvInfo) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *EnvInfo) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *EnvInfo) GetOsRelease() string {
	if m != nil {
		return m.OsRelease
	}
	return ""
}

func (m *EnvInfo) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

type SdkInfo struct {
	AppId                string   `protobuf:"bytes,1,opt,name=AppId,proto3" json:"AppId,omitempty"`
	AppVersion           string   `protobuf:"bytes,2,opt,name=AppVersion,proto3" json:"AppVersion,omitempty"`
	Branch               string   `protobuf:"bytes,3,opt,name=Branch,proto3" json:"Branch,omitempty"`
	Revision             string   `protobuf:"bytes,4,opt,name=Revision,proto3" json:"Revision,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=Type,proto3" json:"Type,omitempty"`
	Version              string   `protobuf:"bytes,6,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SdkInfo) Reset()         { *m = SdkInfo{} }
func (m *SdkInfo) String() string { return proto.CompactTextString(m) }
func (*SdkInfo) ProtoMessage()    {}
func (*SdkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{20}
}

func (m *SdkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkInfo.Unmarshal(m, b)
}
func (m *SdkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkInfo.Marshal(b, m, deterministic)
}
func (m *SdkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkInfo.Merge(m, src)
}
func (m *SdkInfo) XXX_Size() int {
	return xxx_messageInfo_SdkInfo.Size(m)
}
func (m *SdkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SdkInfo proto.InternalMessageInfo

func (m *SdkInfo) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SdkInfo) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *SdkInfo) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *SdkInfo) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *SdkInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SdkInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type CreateApiSessionRequest struct {
	EnvInfo              *EnvInfo `protobuf:"bytes,1,opt,name=envInfo,proto3" json:"envInfo,omitempty"`
	SdkInfo              *SdkInfo `protobuf:"bytes,2,opt,name=sdkInfo,proto3" json:"sdkInfo,omitempty"`
	ConfigTypes          []string `protobuf:"bytes,3,rep,name=configTypes,proto3" json:"configTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateApiSessionRequest) Reset()         { *m = CreateApiSessionRequest{} }
func (m *CreateApiSessionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateApiSessionRequest) ProtoMessage()    {}
func (*CreateApiSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{21}
}

func (m *CreateApiSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateApiSessionRequest.Unmarshal(m, b)
}
func (m *CreateApiSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateApiSessionRequest.Marshal(b, m, deterministic)
}
func (m *CreateApiSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApiSessionRequest.Merge(m, src)
}
func (m *CreateApiSessionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateApiSessionRequest.Size(m)
}
func (m *CreateApiSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApiSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApiSessionRequest proto.InternalMessageInfo

func (m *CreateApiSessionRequest) GetEnvInfo() *EnvInfo {
	if m != nil {
		return m.EnvInfo
	}
	return nil
}

func (m *CreateApiSessionRequest) GetSdkInfo() *SdkInfo {
	if m != nil {
		return m.SdkInfo
	}
	return nil
}

func (m *CreateApiSessionRequest) GetConfigTypes() []string {
	if m != nil {
		return m.ConfigTypes
	}
	return nil
}

type CreateApiSessionResponse struct {
	SessionId                string                          `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Token                    string                          `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	RefreshIntervalSeconds   uint32                          `protobuf:"varint,3,opt,name=refreshIntervalSeconds,proto3" json:"refreshIntervalSeconds,omitempty"`
	IdentityId               string                          `protobuf:"bytes,4,opt,name=identityId,proto3" json:"identityId,omitempty"`
	IdentityName             string                          `protobuf:"bytes,5,opt,name=identityName,proto3" json:"identityName,omitempty"`
	DefaultHostingPrecedence TerminatorPrecedence            `protobuf:"varint,6,opt,name=defaultHostingPrecedence,proto3,enum=ziti.edge_ctrl.pb.TerminatorPrecedence" json:"defaultHostingPrecedence,omitempty"`
	DefaultHostingCost       uint32                          `protobuf:"varint,7,opt,name=defaultHostingCost,proto3" json:"defaultHostingCost,omitempty"`
	AppDataJson              string                          `protobuf:"bytes,8,opt,name=appDataJson,proto3" json:"appDataJson,omitempty"`
	ServicePrecedences       map[string]TerminatorPrecedence `protobuf:"bytes,9,rep,name=servicePrecedences,proto3" json:"servicePrecedences,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=ziti.edge_ctrl.pb.TerminatorPrecedence"`
	ServiceCosts             map[string]uint32               `protobuf:"bytes,10,rep,name=serviceCosts,proto3" json:"serviceCosts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral     struct{}                        `json:"-"`
	XXX_unrecognized         []byte                          `json:"-"`
	XXX_sizecache            int32                           `json:"-"`
}

func (m *CreateApiSessionResponse) Reset()         { *m = CreateApiSessionResponse{} }
func (m *CreateApiSessionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateApiSessionResponse) ProtoMessage()    {}
func (*CreateApiSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{22}
}

func (m *CreateApiSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateApiSessionResponse.Unmarshal(m, b)
}
func (m *CreateApiSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateApiSessionResponse.Marshal(b, m, deterministic)
}
func (m *CreateApiSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApiSessionResponse.Merge(m, src)
}
func (m *CreateApiSessionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateApiSessionResponse.Size(m)
}
func (m *CreateApiSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApiSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApiSessionResponse proto.InternalMessageInfo

func (m *CreateApiSessionResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *CreateApiSessionResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateApiSessionResponse) GetRefreshIntervalSeconds() uint32 {
	if m != nil {
		return m.RefreshIntervalSeconds
	}
	return 0
}

func (m *CreateApiSessionResponse) GetIdentityId() string {
	if m != nil {
		return m.IdentityId
	}
	return ""
}

func (m *CreateApiSessionResponse) GetIdentityName() string {
	if m != nil {
		return m.IdentityName
	}
	return ""
}

func (m *CreateApiSessionResponse) GetDefaultHostingPrecedence() TerminatorPrecedence {
	if m != nil {
		return m.DefaultHostingPrecedence
	}
	return TerminatorPrecedence_Default
}

func (m *CreateApiSessionResponse) GetDefaultHostingCost() uint32 {
	if m != nil {
		return m.DefaultHostingCost
	}
	return 0
}

func (m *CreateApiSessionResponse) GetAppDataJson() string {
	if m != nil {
		return m.AppDataJson
	}
	return ""
}

func (m *CreateApiSessionResponse) GetServicePrecedences() map[string]TerminatorPrecedence {
	if m != nil {
		return m.ServicePrecedences
	}
	return nil
}

func (m *CreateApiSessionResponse) GetServiceCosts() map[string]uint32 {
	if m != nil {
		return m.ServiceCosts
	}
	return nil
}

type CreateCircuitForServiceRequest struct {
	SessionId            string            `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	ServiceName          string            `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	TerminatorIdentity   string            `protobuf:"bytes,3,opt,name=terminatorIdentity,proto3" json:"terminatorIdentity,omitempty"`
	PeerData             map[uint32][]byte `protobuf:"bytes,4,rep,name=peerData,proto3" json:"peerData,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateCircuitForServiceRequest) Reset()         { *m = CreateCircuitForServiceRequest{} }
func (m *CreateCircuitForServiceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCircuitForServiceRequest) ProtoMessage()    {}
func (*CreateCircuitForServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{23}
}

func (m *CreateCircuitForServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCircuitForServiceRequest.Unmarshal(m, b)
}
func (m *CreateCircuitForServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCircuitForServiceRequest.Marshal(b, m, deterministic)
}
func (m *CreateCircuitForServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCircuitForServiceRequest.Merge(m, src)
}
func (m *CreateCircuitForServiceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCircuitForServiceRequest.Size(m)
}
func (m *CreateCircuitForServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCircuitForServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCircuitForServiceRequest proto.InternalMessageInfo

func (m *CreateCircuitForServiceRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *CreateCircuitForServiceRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *CreateCircuitForServiceRequest) GetTerminatorIdentity() string {
	if m != nil {
		return m.TerminatorIdentity
	}
	return ""
}

func (m *CreateCircuitForServiceRequest) GetPeerData() map[uint32][]byte {
	if m != nil {
		return m.PeerData
	}
	return nil
}

type CreateSessionResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionResponse) Reset()         { *m = CreateSessionResponse{} }
func (m *CreateSessionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSessionResponse) ProtoMessage()    {}
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{24}
}

func (m *CreateSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionResponse.Unmarshal(m, b)
}
func (m *CreateSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionResponse.Merge(m, src)
}
func (m *CreateSessionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSessionResponse.Size(m)
}
func (m *CreateSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionResponse proto.InternalMessageInfo

func (m *CreateSessionResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *CreateSessionResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CreateCircuitForServiceResponse struct {
	ApiSession           *CreateApiSessionResponse `protobuf:"bytes,1,opt,name=apiSession,proto3" json:"apiSession,omitempty"`
	Session              *CreateSessionResponse    `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	CircuitId            string                    `protobuf:"bytes,3,opt,name=circuitId,proto3" json:"circuitId,omitempty"`
	Address              string                    `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PeerData             map[uint32][]byte         `protobuf:"bytes,5,rep,name=peerData,proto3" json:"peerData,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CreateCircuitForServiceResponse) Reset()         { *m = CreateCircuitForServiceResponse{} }
func (m *CreateCircuitForServiceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCircuitForServiceResponse) ProtoMessage()    {}
func (*CreateCircuitForServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{25}
}

func (m *CreateCircuitForServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCircuitForServiceResponse.Unmarshal(m, b)
}
func (m *CreateCircuitForServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCircuitForServiceResponse.Marshal(b, m, deterministic)
}
func (m *CreateCircuitForServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCircuitForServiceResponse.Merge(m, src)
}
func (m *CreateCircuitForServiceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCircuitForServiceResponse.Size(m)
}
func (m *CreateCircuitForServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCircuitForServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCircuitForServiceResponse proto.InternalMessageInfo

func (m *CreateCircuitForServiceResponse) GetApiSession() *CreateApiSessionResponse {
	if m != nil {
		return m.ApiSession
	}
	return nil
}

func (m *CreateCircuitForServiceResponse) GetSession() *CreateSessionResponse {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *CreateCircuitForServiceResponse) GetCircuitId() string {
	if m != nil {
		return m.CircuitId
	}
	return ""
}

func (m *CreateCircuitForServiceResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateCircuitForServiceResponse) GetPeerData() map[uint32][]byte {
	if m != nil {
		return m.PeerData
	}
	return nil
}

type ServicesList struct {
	LastUpdate           []byte           `protobuf:"bytes,1,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	Services             []*TunnelService `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ServicesList) Reset()         { *m = ServicesList{} }
func (m *ServicesList) String() string { return proto.CompactTextString(m) }
func (*ServicesList) ProtoMessage()    {}
func (*ServicesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{26}
}

func (m *ServicesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServicesList.Unmarshal(m, b)
}
func (m *ServicesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServicesList.Marshal(b, m, deterministic)
}
func (m *ServicesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServicesList.Merge(m, src)
}
func (m *ServicesList) XXX_Size() int {
	return xxx_messageInfo_ServicesList.Size(m)
}
func (m *ServicesList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServicesList.DiscardUnknown(m)
}

var xxx_messageInfo_ServicesList proto.InternalMessageInfo

func (m *ServicesList) GetLastUpdate() []byte {
	if m != nil {
		return m.LastUpdate
	}
	return nil
}

func (m *ServicesList) GetServices() []*TunnelService {
	if m != nil {
		return m.Services
	}
	return nil
}

type TunnelService struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Permissions          []string `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Encryption           bool     `protobuf:"varint,4,opt,name=encryption,proto3" json:"encryption,omitempty"`
	Config               []byte   `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	Tags                 []byte   `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TunnelService) Reset()         { *m = TunnelService{} }
func (m *TunnelService) String() string { return proto.CompactTextString(m) }
func (*TunnelService) ProtoMessage()    {}
func (*TunnelService) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{27}
}

func (m *TunnelService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TunnelService.Unmarshal(m, b)
}
func (m *TunnelService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TunnelService.Marshal(b, m, deterministic)
}
func (m *TunnelService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TunnelService.Merge(m, src)
}
func (m *TunnelService) XXX_Size() int {
	return xxx_messageInfo_TunnelService.Size(m)
}
func (m *TunnelService) XXX_DiscardUnknown() {
	xxx_messageInfo_TunnelService.DiscardUnknown(m)
}

var xxx_messageInfo_TunnelService proto.InternalMessageInfo

func (m *TunnelService) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TunnelService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TunnelService) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *TunnelService) GetEncryption() bool {
	if m != nil {
		return m.Encryption
	}
	return false
}

func (m *TunnelService) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *TunnelService) GetTags() []byte {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CreateTunnelTerminatorRequest struct {
	ServiceName          string               `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	SessionId            string               `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Address              string               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PeerData             map[uint32][]byte    `protobuf:"bytes,4,rep,name=peerData,proto3" json:"peerData,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cost                 uint32               `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Precedence           TerminatorPrecedence `protobuf:"varint,6,opt,name=precedence,proto3,enum=ziti.edge_ctrl.pb.TerminatorPrecedence" json:"precedence,omitempty"`
	Identity             string               `protobuf:"bytes,7,opt,name=identity,proto3" json:"identity,omitempty"`
	IdentitySecret       []byte               `protobuf:"bytes,8,opt,name=identitySecret,proto3" json:"identitySecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateTunnelTerminatorRequest) Reset()         { *m = CreateTunnelTerminatorRequest{} }
func (m *CreateTunnelTerminatorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTunnelTerminatorRequest) ProtoMessage()    {}
func (*CreateTunnelTerminatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{28}
}

func (m *CreateTunnelTerminatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTunnelTerminatorRequest.Unmarshal(m, b)
}
func (m *CreateTunnelTerminatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTunnelTerminatorRequest.Marshal(b, m, deterministic)
}
func (m *CreateTunnelTerminatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTunnelTerminatorRequest.Merge(m, src)
}
func (m *CreateTunnelTerminatorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTunnelTerminatorRequest.Size(m)
}
func (m *CreateTunnelTerminatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTunnelTerminatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTunnelTerminatorRequest proto.InternalMessageInfo

func (m *CreateTunnelTerminatorRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *CreateTunnelTerminatorRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *CreateTunnelTerminatorRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateTunnelTerminatorRequest) GetPeerData() map[uint32][]byte {
	if m != nil {
		return m.PeerData
	}
	return nil
}

func (m *CreateTunnelTerminatorRequest) GetCost() uint32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *CreateTunnelTerminatorRequest) GetPrecedence() TerminatorPrecedence {
	if m != nil {
		return m.Precedence
	}
	return TerminatorPrecedence_Default
}

func (m *CreateTunnelTerminatorRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *CreateTunnelTerminatorRequest) GetIdentitySecret() []byte {
	if m != nil {
		return m.IdentitySecret
	}
	return nil
}

type CreateTunnelTerminatorResponse struct {
	ApiSession           *CreateApiSessionResponse `protobuf:"bytes,1,opt,name=apiSession,proto3" json:"apiSession,omitempty"`
	Session              *CreateSessionResponse    `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	TerminatorId         string                    `protobuf:"bytes,3,opt,name=terminatorId,proto3" json:"terminatorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CreateTunnelTerminatorResponse) Reset()         { *m = CreateTunnelTerminatorResponse{} }
func (m *CreateTunnelTerminatorResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTunnelTerminatorResponse) ProtoMessage()    {}
func (*CreateTunnelTerminatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{29}
}

func (m *CreateTunnelTerminatorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTunnelTerminatorResponse.Unmarshal(m, b)
}
func (m *CreateTunnelTerminatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTunnelTerminatorResponse.Marshal(b, m, deterministic)
}
func (m *CreateTunnelTerminatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTunnelTerminatorResponse.Merge(m, src)
}
func (m *CreateTunnelTerminatorResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTunnelTerminatorResponse.Size(m)
}
func (m *CreateTunnelTerminatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTunnelTerminatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTunnelTerminatorResponse proto.InternalMessageInfo

func (m *CreateTunnelTerminatorResponse) GetApiSession() *CreateApiSessionResponse {
	if m != nil {
		return m.ApiSession
	}
	return nil
}

func (m *CreateTunnelTerminatorResponse) GetSession() *CreateSessionResponse {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *CreateTunnelTerminatorResponse) GetTerminatorId() string {
	if m != nil {
		return m.TerminatorId
	}
	return ""
}

type UpdateTunnelTerminatorRequest struct {
	TerminatorId         string               `protobuf:"bytes,1,opt,name=terminatorId,proto3" json:"terminatorId,omitempty"`
	Cost                 uint32               `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	Precedence           TerminatorPrecedence `protobuf:"varint,3,opt,name=precedence,proto3,enum=ziti.edge_ctrl.pb.TerminatorPrecedence" json:"precedence,omitempty"`
	UpdatePrecedence     bool                 `protobuf:"varint,4,opt,name=updatePrecedence,proto3" json:"updatePrecedence,omitempty"`
	UpdateCost           bool                 `protobuf:"varint,5,opt,name=updateCost,proto3" json:"updateCost,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateTunnelTerminatorRequest) Reset()         { *m = UpdateTunnelTerminatorRequest{} }
func (m *UpdateTunnelTerminatorRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTunnelTerminatorRequest) ProtoMessage()    {}
func (*UpdateTunnelTerminatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{30}
}

func (m *UpdateTunnelTerminatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTunnelTerminatorRequest.Unmarshal(m, b)
}
func (m *UpdateTunnelTerminatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTunnelTerminatorRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTunnelTerminatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTunnelTerminatorRequest.Merge(m, src)
}
func (m *UpdateTunnelTerminatorRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTunnelTerminatorRequest.Size(m)
}
func (m *UpdateTunnelTerminatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTunnelTerminatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTunnelTerminatorRequest proto.InternalMessageInfo

func (m *UpdateTunnelTerminatorRequest) GetTerminatorId() string {
	if m != nil {
		return m.TerminatorId
	}
	return ""
}

func (m *UpdateTunnelTerminatorRequest) GetCost() uint32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *UpdateTunnelTerminatorRequest) GetPrecedence() TerminatorPrecedence {
	if m != nil {
		return m.Precedence
	}
	return TerminatorPrecedence_Default
}

func (m *UpdateTunnelTerminatorRequest) GetUpdatePrecedence() bool {
	if m != nil {
		return m.UpdatePrecedence
	}
	return false
}

func (m *UpdateTunnelTerminatorRequest) GetUpdateCost() bool {
	if m != nil {
		return m.UpdateCost
	}
	return false
}

type EnrollmentExtendRouterRequest struct {
	ClientCertCsr        string   `protobuf:"bytes,1,opt,name=clientCertCsr,proto3" json:"clientCertCsr,omitempty"`
	ServerCertCsr        string   `protobuf:"bytes,2,opt,name=serverCertCsr,proto3" json:"serverCertCsr,omitempty"`
	RequireVerification  bool     `protobuf:"varint,3,opt,name=requireVerification,proto3" json:"requireVerification,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollmentExtendRouterRequest) Reset()         { *m = EnrollmentExtendRouterRequest{} }
func (m *EnrollmentExtendRouterRequest) String() string { return proto.CompactTextString(m) }
func (*EnrollmentExtendRouterRequest) ProtoMessage()    {}
func (*EnrollmentExtendRouterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{31}
}

func (m *EnrollmentExtendRouterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollmentExtendRouterRequest.Unmarshal(m, b)
}
func (m *EnrollmentExtendRouterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollmentExtendRouterRequest.Marshal(b, m, deterministic)
}
func (m *EnrollmentExtendRouterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollmentExtendRouterRequest.Merge(m, src)
}
func (m *EnrollmentExtendRouterRequest) XXX_Size() int {
	return xxx_messageInfo_EnrollmentExtendRouterRequest.Size(m)
}
func (m *EnrollmentExtendRouterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollmentExtendRouterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollmentExtendRouterRequest proto.InternalMessageInfo

func (m *EnrollmentExtendRouterRequest) GetClientCertCsr() string {
	if m != nil {
		return m.ClientCertCsr
	}
	return ""
}

func (m *EnrollmentExtendRouterRequest) GetServerCertCsr() string {
	if m != nil {
		return m.ServerCertCsr
	}
	return ""
}

func (m *EnrollmentExtendRouterRequest) GetRequireVerification() bool {
	if m != nil {
		return m.RequireVerification
	}
	return false
}

type EnrollmentCertsResponse struct {
	ClientCertPem        string   `protobuf:"bytes,1,opt,name=clientCertPem,proto3" json:"clientCertPem,omitempty"`
	ServerCertPem        string   `protobuf:"bytes,2,opt,name=serverCertPem,proto3" json:"serverCertPem,omitempty"`
	CaCertsPem           string   `protobuf:"bytes,3,opt,name=caCertsPem,proto3" json:"caCertsPem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollmentCertsResponse) Reset()         { *m = EnrollmentCertsResponse{} }
func (m *EnrollmentCertsResponse) String() string { return proto.CompactTextString(m) }
func (*EnrollmentCertsResponse) ProtoMessage()    {}
func (*EnrollmentCertsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{32}
}

func (m *EnrollmentCertsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollmentCertsResponse.Unmarshal(m, b)
}
func (m *EnrollmentCertsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollmentCertsResponse.Marshal(b, m, deterministic)
}
func (m *EnrollmentCertsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollmentCertsResponse.Merge(m, src)
}
func (m *EnrollmentCertsResponse) XXX_Size() int {
	return xxx_messageInfo_EnrollmentCertsResponse.Size(m)
}
func (m *EnrollmentCertsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollmentCertsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollmentCertsResponse proto.InternalMessageInfo

func (m *EnrollmentCertsResponse) GetClientCertPem() string {
	if m != nil {
		return m.ClientCertPem
	}
	return ""
}

func (m *EnrollmentCertsResponse) GetServerCertPem() string {
	if m != nil {
		return m.ServerCertPem
	}
	return ""
}

func (m *EnrollmentCertsResponse) GetCaCertsPem() string {
	if m != nil {
		return m.CaCertsPem
	}
	return ""
}

type EnrollmentExtendRouterVerifyRequest struct {
	ClientCertPem        string   `protobuf:"bytes,1,opt,name=clientCertPem,proto3" json:"clientCertPem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollmentExtendRouterVerifyRequest) Reset()         { *m = EnrollmentExtendRouterVerifyRequest{} }
func (m *EnrollmentExtendRouterVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*EnrollmentExtendRouterVerifyRequest) ProtoMessage()    {}
func (*EnrollmentExtendRouterVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23f46a161f139ee1, []int{33}
}

func (m *EnrollmentExtendRouterVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollmentExtendRouterVerifyRequest.Unmarshal(m, b)
}
func (m *EnrollmentExtendRouterVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollmentExtendRouterVerifyRequest.Marshal(b, m, deterministic)
}
func (m *EnrollmentExtendRouterVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollmentExtendRouterVerifyRequest.Merge(m, src)
}
func (m *EnrollmentExtendRouterVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_EnrollmentExtendRouterVerifyRequest.Size(m)
}
func (m *EnrollmentExtendRouterVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollmentExtendRouterVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollmentExtendRouterVerifyRequest proto.InternalMessageInfo

func (m *EnrollmentExtendRouterVerifyRequest) GetClientCertPem() string {
	if m != nil {
		return m.ClientCertPem
	}
	return ""
}

func init() {
	proto.RegisterEnum("ziti.edge_ctrl.pb.ContentType", ContentType_name, ContentType_value)
	proto.RegisterEnum("ziti.edge_ctrl.pb.SessionType", SessionType_name, SessionType_value)
	proto.RegisterEnum("ziti.edge_ctrl.pb.Header", Header_name, Header_value)
	proto.RegisterEnum("ziti.edge_ctrl.pb.TerminatorPrecedence", TerminatorPrecedence_name, TerminatorPrecedence_value)
	proto.RegisterType((*ServerHello)(nil), "ziti.edge_ctrl.pb.ServerHello")
	proto.RegisterMapType((map[string]string)(nil), "ziti.edge_ctrl.pb.ServerHello.DataEntry")
	proto.RegisterType((*ClientHello)(nil), "ziti.edge_ctrl.pb.ClientHello")
	proto.RegisterMapType((map[string]string)(nil), "ziti.edge_ctrl.pb.ClientHello.DataEntry")
	proto.RegisterType((*Error)(nil), "ziti.edge_ctrl.pb.Error")
	proto.RegisterType((*Service)(nil), "ziti.edge_ctrl.pb.Service")
	proto.RegisterType((*Session)(nil), "ziti.edge_ctrl.pb.Session")
	proto.RegisterType((*ApiSession)(nil), "ziti.edge_ctrl.pb.ApiSession")
	proto.RegisterType((*ApiSessionAdded)(nil), "ziti.edge_ctrl.pb.ApiSessionAdded")
	proto.RegisterType((*ApiSessionUpdated)(nil), "ziti.edge_ctrl.pb.ApiSessionUpdated")
	proto.RegisterType((*ApiSessionRemoved)(nil), "ziti.edge_ctrl.pb.ApiSessionRemoved")
	proto.RegisterType((*ApiSessionHeartbeat)(nil), "ziti.edge_ctrl.pb.ApiSessionHeartbeat")
	proto.RegisterType((*SessionRemoved)(nil), "ziti.edge_ctrl.pb.SessionRemoved")
	proto.RegisterType((*RequestClientReSync)(nil), "ziti.edge_ctrl.pb.RequestClientReSync")
	proto.RegisterType((*CreateCircuitRequest)(nil), "ziti.edge_ctrl.pb.CreateCircuitRequest")
	proto.RegisterMapType((map[uint32][]byte)(nil), "ziti.edge_ctrl.pb.CreateCircuitRequest.PeerDataEntry")
	proto.RegisterType((*CreateCircuitResponse)(nil), "ziti.edge_ctrl.pb.CreateCircuitResponse")
	proto.RegisterMapType((map[uint32][]byte)(nil), "ziti.edge_ctrl.pb.CreateCircuitResponse.PeerDataEntry")
	proto.RegisterType((*CreateTerminatorRequest)(nil), "ziti.edge_ctrl.pb.CreateTerminatorRequest")
	proto.RegisterMapType((map[uint32][]byte)(nil), "ziti.edge_ctrl.pb.CreateTerminatorRequest.PeerDataEntry")
	proto.RegisterType((*RemoveTerminatorRequest)(nil), "ziti.edge_ctrl.pb.RemoveTerminatorRequest")
	proto.RegisterType((*UpdateTerminatorRequest)(nil), "ziti.edge_ctrl.pb.UpdateTerminatorRequest")
	proto.RegisterType((*HealthEventRequest)(nil), "ziti.edge_ctrl.pb.HealthEventRequest")
	proto.RegisterType((*ValidateSessionsRequest)(nil), "ziti.edge_ctrl.pb.ValidateSessionsRequest")
	proto.RegisterType((*EnvInfo)(nil), "ziti.edge_ctrl.pb.EnvInfo")
	proto.RegisterType((*SdkInfo)(nil), "ziti.edge_ctrl.pb.SdkInfo")
	proto.RegisterType((*CreateApiSessionRequest)(nil), "ziti.edge_ctrl.pb.CreateApiSessionRequest")
	proto.RegisterType((*CreateApiSessionResponse)(nil), "ziti.edge_ctrl.pb.CreateApiSessionResponse")
	proto.RegisterMapType((map[string]uint32)(nil), "ziti.edge_ctrl.pb.CreateApiSessionResponse.ServiceCostsEntry")
	proto.RegisterMapType((map[string]TerminatorPrecedence)(nil), "ziti.edge_ctrl.pb.CreateApiSessionResponse.ServicePrecedencesEntry")
	proto.RegisterType((*CreateCircuitForServiceRequest)(nil), "ziti.edge_ctrl.pb.CreateCircuitForServiceRequest")
	proto.RegisterMapType((map[uint32][]byte)(nil), "ziti.edge_ctrl.pb.CreateCircuitForServiceRequest.PeerDataEntry")
	proto.RegisterType((*CreateSessionResponse)(nil), "ziti.edge_ctrl.pb.CreateSessionResponse")
	proto.RegisterType((*CreateCircuitForServiceResponse)(nil), "ziti.edge_ctrl.pb.CreateCircuitForServiceResponse")
	proto.RegisterMapType((map[uint32][]byte)(nil), "ziti.edge_ctrl.pb.CreateCircuitForServiceResponse.PeerDataEntry")
	proto.RegisterType((*ServicesList)(nil), "ziti.edge_ctrl.pb.ServicesList")
	proto.RegisterType((*TunnelService)(nil), "ziti.edge_ctrl.pb.TunnelService")
	proto.RegisterType((*CreateTunnelTerminatorRequest)(nil), "ziti.edge_ctrl.pb.CreateTunnelTerminatorRequest")
	proto.RegisterMapType((map[uint32][]byte)(nil), "ziti.edge_ctrl.pb.CreateTunnelTerminatorRequest.PeerDataEntry")
	proto.RegisterType((*CreateTunnelTerminatorResponse)(nil), "ziti.edge_ctrl.pb.CreateTunnelTerminatorResponse")
	proto.RegisterType((*UpdateTunnelTerminatorRequest)(nil), "ziti.edge_ctrl.pb.UpdateTunnelTerminatorRequest")
	proto.RegisterType((*EnrollmentExtendRouterRequest)(nil), "ziti.edge_ctrl.pb.EnrollmentExtendRouterRequest")
	proto.RegisterType((*EnrollmentCertsResponse)(nil), "ziti.edge_ctrl.pb.EnrollmentCertsResponse")
	proto.RegisterType((*EnrollmentExtendRouterVerifyRequest)(nil), "ziti.edge_ctrl.pb.EnrollmentExtendRouterVerifyRequest")
}

func init() {
	proto.RegisterFile("edge_ctrl.proto", fileDescriptor_23f46a161f139ee1)
}

var fileDescriptor_23f46a161f139ee1 = []byte{
	// 2190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x59, 0xcd, 0x73, 0x1c, 0x47,
	0x15, 0xf7, 0xec, 0x4a, 0xda, 0xdd, 0xb7, 0x2b, 0x79, 0xdd, 0xb1, 0xa3, 0x8d, 0x12, 0x2b, 0xf2,
	0x24, 0x85, 0x85, 0xa8, 0xc8, 0x94, 0x08, 0x21, 0x15, 0x22, 0x8c, 0x2d, 0xcb, 0x48, 0x98, 0x8a,
	0xc5, 0x48, 0xf8, 0x60, 0x3e, 0x52, 0xa3, 0x99, 0x96, 0x34, 0xe5, 0xd1, 0xcc, 0xd0, 0xd3, 0xab,
	0x42, 0xdc, 0xc3, 0x81, 0x3b, 0x37, 0xaf, 0x44, 0x72, 0xa1, 0x8a, 0x03, 0x05, 0x84, 0x6f, 0xf8,
	0x03, 0x38, 0xf0, 0x71, 0xe2, 0xce, 0x91, 0x8f, 0xf0, 0xfd, 0x71, 0x23, 0x50, 0xfd, 0x7a, 0x7a,
	0xa6, 0x67, 0x67, 0x46, 0xb2, 0x12, 0x09, 0xb8, 0x4d, 0xbf, 0x7e, 0xfd, 0xeb, 0xf7, 0xfa, 0xbd,
	0x7e, 0x1f, 0x3d, 0x70, 0x9e, 0xba, 0xdb, 0xf4, 0x55, 0x87, 0x33, 0x7f, 0x3e, 0x62, 0x21, 0x0f,
	0xc9, 0x85, 0x2f, 0x7a, 0xdc, 0x9b, 0xd7, 0xa8, 0x9b, 0xe6, 0x81, 0x01, 0xed, 0x75, 0xca, 0xf6,
	0x28, 0x5b, 0xa1, 0xbe, 0x1f, 0x92, 0x1e, 0x34, 0xf6, 0x28, 0x8b, 0xbd, 0x30, 0xe8, 0x19, 0x33,
	0xc6, 0x6c, 0xcb, 0x52, 0x43, 0xf2, 0x32, 0x8c, 0xb8, 0x36, 0xb7, 0x7b, 0xb5, 0x99, 0xfa, 0x6c,
	0x7b, 0x61, 0x76, 0xbe, 0x80, 0x35, 0xaf, 0xe1, 0xcc, 0xdf, 0xb2, 0xb9, 0xbd, 0x1c, 0x70, 0xb6,
	0x6f, 0xe1, 0xaa, 0xa9, 0x0f, 0x41, 0x2b, 0x25, 0x91, 0x2e, 0xd4, 0x1f, 0xd0, 0xfd, 0x64, 0x03,
	0xf1, 0x49, 0x2e, 0xc2, 0xe8, 0x9e, 0xed, 0xf7, 0x69, 0xaf, 0x86, 0x34, 0x39, 0x78, 0xa9, 0xf6,
	0xa2, 0x61, 0xbe, 0x6d, 0x40, 0x7b, 0xc9, 0xf7, 0x68, 0xc0, 0x8f, 0x13, 0x70, 0x0a, 0x9a, 0x3b,
	0x61, 0xcc, 0x03, 0x7b, 0x57, 0xc1, 0xa4, 0x63, 0xf2, 0x14, 0xb4, 0xf0, 0x08, 0x9c, 0xd0, 0x8f,
	0x7b, 0xf5, 0x99, 0xfa, 0x6c, 0xcb, 0xca, 0x08, 0xa9, 0x6a, 0x23, 0x95, 0xaa, 0x69, 0x12, 0x0c,
	0xab, 0x46, 0x9e, 0x85, 0x71, 0x05, 0xb5, 0x16, 0x32, 0x1e, 0xf7, 0x46, 0x11, 0x3f, 0x4f, 0x7c,
	0xe7, 0x07, 0x70, 0x07, 0x46, 0x97, 0x19, 0x0b, 0x19, 0x21, 0x30, 0xe2, 0x84, 0x2e, 0x4d, 0x56,
	0xe1, 0xb7, 0x38, 0x8d, 0x5d, 0x1a, 0xc7, 0xf6, 0xb6, 0x5a, 0xa8, 0x86, 0x02, 0xd0, 0xb1, 0xfb,
	0x31, 0xed, 0xd5, 0x25, 0x20, 0x0e, 0xcc, 0xcf, 0x42, 0x43, 0x58, 0xc9, 0x73, 0x28, 0x99, 0x80,
	0x9a, 0xe7, 0x26, 0x60, 0x35, 0xcf, 0x15, 0xf0, 0xda, 0xd1, 0xe1, 0x37, 0x99, 0x07, 0x42, 0x03,
	0x87, 0xed, 0x47, 0xdc, 0x0b, 0x03, 0x8b, 0x7e, 0xbe, 0xef, 0x31, 0xea, 0x22, 0x62, 0xd3, 0x2a,
	0x99, 0x31, 0xff, 0x65, 0x08, 0xfc, 0x18, 0xcd, 0x71, 0x11, 0x46, 0x79, 0xf8, 0x80, 0x2a, 0x33,
	0xc9, 0x01, 0x59, 0x80, 0x11, 0xbe, 0x1f, 0xc9, 0x5d, 0x26, 0x16, 0xa6, 0x4b, 0xbd, 0x08, 0xd7,
	0x6f, 0xec, 0x47, 0xd4, 0x42, 0x5e, 0x32, 0x07, 0x5d, 0x87, 0x32, 0x7e, 0xdb, 0x0b, 0xb6, 0x29,
	0x8b, 0x98, 0x17, 0x70, 0x65, 0xc3, 0x02, 0x5d, 0x68, 0xd1, 0x67, 0x7e, 0x8c, 0xa6, 0x6c, 0x59,
	0xf8, 0x4d, 0x9e, 0x87, 0x46, 0x2c, 0x95, 0xee, 0x8d, 0xce, 0x18, 0xb3, 0xed, 0x85, 0xa9, 0x0a,
	0xe7, 0xf5, 0x1c, 0x6a, 0x29, 0xd6, 0xe4, 0x7c, 0x1a, 0xe9, 0xf9, 0x98, 0xd0, 0xb1, 0x23, 0x2f,
	0x91, 0x6e, 0xd5, 0xed, 0x35, 0x71, 0x26, 0x47, 0x33, 0x3f, 0x07, 0x70, 0x23, 0x1d, 0x57, 0x9c,
	0x40, 0x99, 0x36, 0xb5, 0x0a, 0x6d, 0xa4, 0x0c, 0x75, 0x25, 0x83, 0xc9, 0xe1, 0x7c, 0x86, 0x7f,
	0xc3, 0x75, 0xa9, 0x4b, 0x66, 0xa0, 0xed, 0xc5, 0xb7, 0xfb, 0xbe, 0xbf, 0xce, 0x6d, 0x2e, 0x9d,
	0xa3, 0x69, 0xe9, 0x24, 0x72, 0x1d, 0xda, 0x99, 0x90, 0x71, 0x72, 0x7f, 0x2f, 0x97, 0x1c, 0x41,
	0x06, 0x6d, 0xe9, 0x2b, 0xcc, 0x0d, 0xb8, 0x90, 0x4d, 0x7d, 0x2a, 0x72, 0x6d, 0x4e, 0xdd, 0x61,
	0x54, 0xe3, 0xc4, 0xa8, 0x8b, 0x3a, 0xaa, 0x45, 0x77, 0xc3, 0x3d, 0xea, 0x92, 0xc7, 0x61, 0x0c,
	0x4f, 0x49, 0x02, 0xb6, 0xac, 0x64, 0x24, 0x2e, 0x8c, 0xe7, 0xaa, 0x73, 0x12, 0x9f, 0xe6, 0x73,
	0xf0, 0x58, 0xb6, 0x7c, 0x85, 0xda, 0x8c, 0x6f, 0x52, 0x9b, 0x57, 0x01, 0x98, 0x2f, 0xc1, 0xc4,
	0xbb, 0xd9, 0x4a, 0x78, 0x38, 0x8d, 0xb9, 0x0c, 0x03, 0x16, 0x5d, 0xdf, 0x0f, 0x1c, 0x01, 0xc0,
	0xa8, 0x1d, 0xa7, 0x81, 0x28, 0x19, 0x99, 0x07, 0x35, 0xb8, 0xb8, 0xc4, 0xa8, 0xcd, 0xe9, 0x92,
	0xc7, 0x9c, 0xbe, 0xc7, 0x93, 0xc5, 0xc2, 0x83, 0xe2, 0xc4, 0xb9, 0x35, 0xb7, 0xc8, 0xd1, 0x04,
	0xcf, 0x56, 0xd1, 0x33, 0x72, 0x34, 0x71, 0x2b, 0x39, 0x65, 0xbb, 0x5e, 0x60, 0xf3, 0x90, 0xad,
	0xba, 0x34, 0xe0, 0x1e, 0xdf, 0x4f, 0xbc, 0xa4, 0x64, 0x86, 0x7c, 0x12, 0x9a, 0x11, 0xa5, 0xec,
	0x56, 0x16, 0xe2, 0x3e, 0x58, 0x16, 0xe2, 0x4a, 0x44, 0x9e, 0x5f, 0x4b, 0xd6, 0xc9, 0x78, 0x97,
	0xc2, 0x4c, 0x7d, 0x18, 0xc6, 0x73, 0x53, 0x7a, 0x44, 0x1b, 0x2f, 0x89, 0x68, 0x1d, 0x3d, 0xa2,
	0xfd, 0xda, 0x80, 0x4b, 0x43, 0xbb, 0xc5, 0x51, 0x18, 0xc4, 0x18, 0xa6, 0x1d, 0x49, 0x5a, 0x55,
	0xa1, 0x29, 0x23, 0x88, 0x60, 0x67, 0xbb, 0x2e, 0xa3, 0x71, 0xac, 0x82, 0x5d, 0x32, 0x24, 0x96,
	0xa6, 0x61, 0x1d, 0x35, 0x7c, 0xe1, 0x78, 0x0d, 0xe5, 0x9e, 0x67, 0xa3, 0xe2, 0x57, 0xea, 0x30,
	0x29, 0xb7, 0xdb, 0x48, 0xed, 0x71, 0xda, 0x6e, 0xb0, 0x51, 0x50, 0xfa, 0xc5, 0x4a, 0xa5, 0x0b,
	0x52, 0x54, 0xa9, 0x2d, 0xb3, 0x4c, 0xcc, 0x7b, 0x23, 0xa8, 0x26, 0x7e, 0x93, 0x8f, 0x01, 0x44,
	0x8c, 0x3a, 0xd4, 0xa5, 0x41, 0x12, 0x43, 0x27, 0x16, 0xae, 0x96, 0xec, 0x95, 0xed, 0xb2, 0x96,
	0xb2, 0x5b, 0xda, 0x52, 0x91, 0xa2, 0x3d, 0xe5, 0xaf, 0x63, 0x32, 0x45, 0xab, 0x31, 0x79, 0x0f,
	0x4c, 0xa8, 0xef, 0x75, 0xea, 0x30, 0xca, 0x31, 0xf6, 0x76, 0xac, 0x21, 0xea, 0xbb, 0xb3, 0xcb,
	0x6b, 0x06, 0x4c, 0xca, 0x00, 0x70, 0x76, 0x76, 0x31, 0xa1, 0xa3, 0x5f, 0xc2, 0xe4, 0x62, 0xe6,
	0x68, 0xe6, 0x37, 0x6a, 0x30, 0x29, 0x23, 0xe9, 0xff, 0x54, 0x8e, 0xb3, 0xb5, 0xf6, 0x1c, 0x74,
	0xfb, 0xa8, 0x63, 0x36, 0x8f, 0x56, 0x6f, 0x5a, 0x05, 0x3a, 0x99, 0x06, 0x90, 0xb4, 0x25, 0x21,
	0x4e, 0x03, 0xb9, 0x34, 0x8a, 0xf9, 0x86, 0x01, 0x64, 0x85, 0xda, 0x3e, 0xdf, 0x59, 0xde, 0xc3,
	0x10, 0xfc, 0xdf, 0x3f, 0xab, 0x19, 0x68, 0x3b, 0x3b, 0xd4, 0x79, 0xb0, 0x66, 0xc7, 0x31, 0x75,
	0xf1, 0xc8, 0x9a, 0x96, 0x4e, 0x32, 0xaf, 0xc3, 0xe4, 0x3d, 0xdb, 0xf7, 0x84, 0xd0, 0x2a, 0xcd,
	0x29, 0x41, 0x9f, 0x85, 0x71, 0x5d, 0x28, 0x95, 0x74, 0xf2, 0x44, 0xd3, 0x83, 0xc6, 0x72, 0xb0,
	0xb7, 0x1a, 0x6c, 0x85, 0xc2, 0x32, 0x36, 0x73, 0x76, 0x54, 0xb5, 0x27, 0xbe, 0x45, 0x39, 0x70,
	0x57, 0xc5, 0xbe, 0xda, 0xdd, 0x58, 0x84, 0xcb, 0xbb, 0xb1, 0x45, 0x7d, 0x6a, 0xa7, 0x75, 0x5e,
	0x46, 0x90, 0xb3, 0xf7, 0x92, 0x5a, 0x79, 0x44, 0xcd, 0x26, 0x04, 0xf3, 0x75, 0x51, 0xaa, 0xb9,
	0x0f, 0x70, 0xaf, 0x8b, 0x30, 0x7a, 0x23, 0x8a, 0xd2, 0x90, 0x2b, 0x07, 0xc2, 0x24, 0x37, 0xa2,
	0x48, 0x01, 0xc8, 0x5d, 0x35, 0x8a, 0xc8, 0x7f, 0x37, 0x99, 0x1d, 0x38, 0x3b, 0xc9, 0xd6, 0xc9,
	0x48, 0x5c, 0x72, 0x8b, 0xee, 0x79, 0xda, 0xb6, 0xe9, 0x58, 0x68, 0x25, 0x0a, 0x3b, 0xf4, 0xaa,
	0x96, 0x85, 0xdf, 0x22, 0xac, 0xab, 0x4d, 0x64, 0x4c, 0x50, 0x43, 0xf3, 0x6b, 0x86, 0x8a, 0xa2,
	0x7a, 0xa5, 0x20, 0x0f, 0xf4, 0x79, 0x68, 0x50, 0x79, 0x54, 0x28, 0x75, 0x79, 0x51, 0x97, 0x1c,
	0xa6, 0xa5, 0x58, 0xb1, 0x14, 0x94, 0x4a, 0xa3, 0x42, 0x15, 0xa5, 0xa0, 0xe4, 0xb0, 0x14, 0x2b,
	0x5a, 0x3e, 0x0c, 0xb6, 0xbc, 0x6d, 0x21, 0xaf, 0xaa, 0x3d, 0x75, 0x92, 0xf9, 0xe5, 0x31, 0xe8,
	0x15, 0x25, 0xcd, 0xb2, 0x5a, 0x9c, 0x96, 0x8d, 0x49, 0x56, 0x4b, 0x09, 0x59, 0x95, 0x58, 0xd3,
	0xab, 0xc4, 0x17, 0xe0, 0x71, 0x46, 0xb7, 0x18, 0x8d, 0x77, 0x56, 0x03, 0x4e, 0xd9, 0x9e, 0xed,
	0xaf, 0x53, 0x27, 0x0c, 0xdc, 0x18, 0x0f, 0x7b, 0xdc, 0xaa, 0x98, 0x15, 0x46, 0x53, 0xf1, 0x72,
	0xd5, 0x4d, 0x8e, 0x5f, 0xa3, 0x08, 0x47, 0x57, 0xa3, 0x57, 0x44, 0xb5, 0x2f, 0x0d, 0x91, 0xa3,
	0x11, 0x07, 0x7a, 0x2e, 0xdd, 0xb2, 0xfb, 0x3e, 0x5f, 0x09, 0x63, 0xee, 0x05, 0xdb, 0x43, 0xf7,
	0xf7, 0x04, 0xe1, 0xa0, 0x12, 0x48, 0x14, 0x31, 0xf9, 0xb9, 0xf4, 0xe2, 0x8f, 0x5b, 0x25, 0x33,
	0xc2, 0x06, 0x76, 0x14, 0x89, 0xa8, 0xff, 0x71, 0x51, 0x72, 0xc9, 0xea, 0x5b, 0x27, 0x91, 0x18,
	0x48, 0x52, 0xbb, 0x67, 0xdb, 0xc4, 0xbd, 0x16, 0x66, 0xc6, 0xa5, 0xca, 0xcc, 0x58, 0xb4, 0x97,
	0x6a, 0x05, 0x34, 0x14, 0x99, 0x24, 0x4b, 0xe0, 0x89, 0x2d, 0x02, 0x10, 0x52, 0x85, 0x94, 0x71,
	0x0f, 0x70, 0xbb, 0xc5, 0x77, 0xb0, 0x1d, 0xae, 0x97, 0x1b, 0xe5, 0x20, 0xa7, 0x02, 0x98, 0xac,
	0x90, 0xa8, 0xa4, 0x8f, 0x5c, 0xd4, 0x53, 0xdf, 0x09, 0x0c, 0x95, 0xe5, 0xc8, 0xa9, 0xeb, 0x70,
	0xa1, 0x20, 0xd2, 0x71, 0x1d, 0xeb, 0xb8, 0x9e, 0x64, 0xbf, 0x5e, 0x83, 0xe9, 0x5c, 0xad, 0x75,
	0x3b, 0x64, 0xaa, 0xbd, 0x4a, 0x6e, 0xef, 0xd1, 0x57, 0x62, 0x06, 0xda, 0xc9, 0x09, 0xbc, 0x92,
	0x75, 0xa4, 0x3a, 0xe9, 0xc4, 0x25, 0xf0, 0xa7, 0x0b, 0x25, 0xf0, 0xf5, 0xe3, 0x0a, 0xc4, 0x82,
	0xd0, 0x67, 0x53, 0x29, 0xde, 0x51, 0xb5, 0xf0, 0x29, 0x44, 0x0d, 0xf3, 0xb5, 0x3a, 0x3c, 0x5d,
	0xa9, 0x44, 0x82, 0x7b, 0x07, 0x20, 0x6b, 0xc3, 0x92, 0xd8, 0xf9, 0xbe, 0x13, 0xf8, 0xab, 0xa5,
	0x2d, 0x27, 0x37, 0x45, 0x6b, 0x1d, 0xa7, 0x09, 0xa2, 0xe2, 0xf1, 0xa4, 0x4c, 0x3f, 0x4b, 0x2d,
	0xcc, 0x17, 0xfd, 0xf5, 0x23, 0x8a, 0xfe, 0x91, 0x7c, 0xd1, 0xff, 0x19, 0xcd, 0xa6, 0xa3, 0x68,
	0xd3, 0x8f, 0x9e, 0xc4, 0xa6, 0x67, 0x59, 0xfe, 0xfb, 0xd0, 0x49, 0xf6, 0x89, 0x3f, 0xe1, 0xc5,
	0x5c, 0x44, 0x65, 0xdf, 0x8e, 0xb9, 0xac, 0xf8, 0x10, 0xa2, 0x63, 0x69, 0x14, 0xf2, 0x32, 0x34,
	0x13, 0xef, 0x56, 0xfd, 0xf9, 0x4c, 0xd9, 0xc5, 0xed, 0x07, 0x01, 0xf5, 0x95, 0x02, 0xe9, 0x0a,
	0x91, 0xca, 0xc7, 0x73, 0x73, 0x8f, 0xf4, 0xb6, 0x33, 0x03, 0xed, 0x48, 0x5c, 0x94, 0xa4, 0x81,
	0x4f, 0x92, 0x9a, 0x46, 0x12, 0x52, 0x67, 0x6f, 0x3c, 0x49, 0xbd, 0xa3, 0x51, 0x44, 0x01, 0x20,
	0x73, 0x20, 0x66, 0x91, 0x8e, 0x95, 0x8c, 0xc4, 0x6e, 0xdc, 0xde, 0x8e, 0x31, 0x57, 0x74, 0x2c,
	0xfc, 0x36, 0xdf, 0xac, 0xc3, 0xe5, 0xa4, 0x15, 0x41, 0x49, 0x8b, 0x65, 0xef, 0xd0, 0xa5, 0x37,
	0x8a, 0x97, 0x3e, 0x77, 0x23, 0x6a, 0xc3, 0x37, 0x42, 0x73, 0x94, 0x7a, 0xde, 0x51, 0xee, 0x17,
	0x2e, 0xff, 0x47, 0xaa, 0x1b, 0xa5, 0x72, 0xe9, 0x8e, 0x6d, 0x97, 0x46, 0x2b, 0x0b, 0xe8, 0xb1,
	0xd3, 0x69, 0x97, 0x1a, 0xc7, 0xb6, 0x4b, 0xcd, 0xd3, 0x6f, 0x97, 0x7e, 0x65, 0xa8, 0x48, 0x5e,
	0x3c, 0x97, 0xff, 0xd7, 0x70, 0xf2, 0x28, 0xed, 0xd7, 0x5b, 0x06, 0x5c, 0x4e, 0xda, 0xaf, 0x0a,
	0x6f, 0x1c, 0x46, 0x31, 0x8e, 0x68, 0x9e, 0x6a, 0x95, 0xb6, 0xaf, 0x9f, 0x6e, 0xf3, 0x34, 0xf2,
	0x48, 0xcd, 0xd3, 0x68, 0xa1, 0x79, 0x1a, 0x18, 0x70, 0x79, 0x39, 0x60, 0xa1, 0xef, 0xef, 0xd2,
	0x80, 0x2f, 0x7f, 0x81, 0xd3, 0xc0, 0xb5, 0xc2, 0x3e, 0xa7, 0x4c, 0x6b, 0x4f, 0x1c, 0x7c, 0xdb,
	0x5a, 0xa2, 0x8c, 0x2f, 0xc5, 0x2c, 0xd1, 0x37, 0x4f, 0x94, 0x4d, 0x0c, 0xdb, 0xa3, 0x4c, 0x71,
	0xc9, 0x4b, 0x98, 0x27, 0x92, 0xf7, 0xc3, 0x63, 0x4c, 0x3e, 0x08, 0xdf, 0xa3, 0xcc, 0xdb, 0xf2,
	0x1c, 0x1b, 0xe3, 0x87, 0x7c, 0x35, 0x2e, 0x9b, 0xc2, 0xae, 0x3c, 0x93, 0x4f, 0xe0, 0xc4, 0xa9,
	0x7f, 0xe5, 0x24, 0x5b, 0xa3, 0xbb, 0x45, 0xc9, 0xd6, 0xe8, 0x6e, 0x5e, 0x32, 0xc1, 0x55, 0x90,
	0x4c, 0x70, 0x4d, 0x03, 0x38, 0x36, 0xc2, 0x0b, 0x16, 0xe9, 0x18, 0x1a, 0xc5, 0xbc, 0x03, 0xcf,
	0x94, 0x1f, 0x13, 0x4a, 0xbb, 0x5f, 0x7a, 0x58, 0x55, 0x22, 0xcd, 0xfd, 0xb4, 0x05, 0xed, 0xa5,
	0x30, 0xe0, 0x34, 0xe0, 0xd8, 0xe6, 0x34, 0x61, 0xe4, 0x3e, 0x65, 0x61, 0xf7, 0x1c, 0xb9, 0x04,
	0xe7, 0xb5, 0x5f, 0x25, 0x62, 0xb2, 0xfb, 0xd5, 0x87, 0x86, 0x20, 0x6b, 0xbf, 0x19, 0x90, 0xfc,
	0xfa, 0x43, 0x83, 0x9c, 0x87, 0x16, 0xbe, 0xff, 0x23, 0xe1, 0x8d, 0x87, 0x06, 0xe9, 0x01, 0xc9,
	0x3f, 0x65, 0xe2, 0xcc, 0x97, 0x06, 0x06, 0x79, 0x42, 0x7f, 0x13, 0xc5, 0xe7, 0x61, 0x9c, 0xfa,
	0xcd, 0xc0, 0x20, 0x4f, 0xc2, 0xa5, 0xc2, 0x1b, 0x2e, 0x4e, 0xfe, 0x76, 0x78, 0x52, 0x07, 0xfd,
	0xdd, 0xc0, 0x20, 0x97, 0x61, 0xb2, 0xe4, 0xa1, 0x15, 0xa7, 0x7f, 0x2f, 0xa7, 0x4b, 0x1e, 0x47,
	0x71, 0xfa, 0xad, 0x81, 0x41, 0xa6, 0x55, 0x5f, 0x94, 0x7f, 0x58, 0xc4, 0xf9, 0x3f, 0x0c, 0x0c,
	0xf2, 0x34, 0x3c, 0x51, 0xfa, 0x2c, 0x87, 0x0c, 0x7f, 0x1c, 0x18, 0xe4, 0x0a, 0x3c, 0x59, 0xf1,
	0x84, 0x85, 0x2c, 0x7f, 0x1a, 0x18, 0xc4, 0x84, 0xa7, 0x8a, 0x2c, 0x1a, 0xcc, 0x9f, 0x25, 0x4c,
	0xc5, 0x7b, 0x0b, 0xb2, 0xfc, 0x45, 0xc2, 0x14, 0x59, 0x34, 0x98, 0xbf, 0x4a, 0x98, 0x8a, 0xe7,
	0x23, 0x64, 0xf9, 0x9b, 0x84, 0x29, 0xb2, 0x68, 0x30, 0x7f, 0x97, 0x30, 0x15, 0x0f, 0x05, 0xc8,
	0xf2, 0x8f, 0x01, 0x7a, 0x83, 0xf6, 0xde, 0x81, 0xe4, 0x7f, 0x0e, 0x0c, 0xd2, 0x05, 0x90, 0x2e,
	0x8a, 0x94, 0x9f, 0x1d, 0x20, 0x56, 0xc5, 0xdd, 0x41, 0x96, 0x9f, 0x1f, 0x18, 0xe4, 0x2a, 0x5c,
	0x39, 0xf2, 0xfa, 0x23, 0xe3, 0x2f, 0x0e, 0x0c, 0xf2, 0x1c, 0x5c, 0x7d, 0x84, 0x0b, 0x80, 0xec,
	0xbf, 0x3c, 0xd0, 0x6c, 0x53, 0x68, 0xcf, 0x91, 0xe5, 0x9b, 0x87, 0x9a, 0x6d, 0x8a, 0x91, 0x1f,
	0x79, 0xbe, 0x75, 0x68, 0x90, 0x59, 0x30, 0x8f, 0xae, 0xbc, 0x91, 0xf3, 0xdb, 0x87, 0x06, 0x79,
	0x2f, 0x3c, 0x73, 0x4c, 0x3d, 0x87, 0xac, 0x6f, 0x1e, 0xa2, 0x5f, 0x8a, 0xd2, 0x4b, 0x95, 0x61,
	0x3a, 0xd2, 0x77, 0x0e, 0x0d, 0x75, 0x07, 0x3d, 0x87, 0x0a, 0x2e, 0x24, 0x7f, 0xf7, 0x10, 0x4f,
	0xea, 0xc8, 0x3a, 0x00, 0x19, 0xbf, 0xa7, 0xcb, 0x5c, 0x95, 0x18, 0x91, 0xf3, 0xfb, 0x12, 0xf2,
	0xc8, 0x54, 0x83, 0x8c, 0x3f, 0x90, 0x90, 0x55, 0x8c, 0x1a, 0xe4, 0x0f, 0x25, 0x64, 0xe2, 0x62,
	0x47, 0x40, 0xfe, 0x48, 0x42, 0x56, 0x31, 0x6a, 0x90, 0x3f, 0x3e, 0xc4, 0x10, 0x20, 0x79, 0x86,
	0x9d, 0xee, 0x27, 0x87, 0xc6, 0xdc, 0x15, 0x68, 0x6b, 0x7f, 0xe5, 0x44, 0x24, 0xbb, 0xe5, 0xd9,
	0x7e, 0xf7, 0x9c, 0xf8, 0xba, 0xe9, 0x05, 0x6e, 0xd7, 0x98, 0x5b, 0x84, 0xb1, 0x15, 0x6a, 0xbb,
	0x94, 0x91, 0x09, 0x00, 0xf9, 0x95, 0x44, 0xbb, 0x0b, 0xd0, 0xd9, 0xd0, 0xb2, 0x66, 0xf7, 0xed,
	0x06, 0xe9, 0x42, 0x7b, 0x29, 0x7b, 0x36, 0xeb, 0xfe, 0xbb, 0x31, 0xb7, 0x08, 0x17, 0xcb, 0x32,
	0x22, 0x69, 0x43, 0xe3, 0x96, 0x7c, 0x0b, 0xe8, 0x9e, 0x23, 0x1d, 0x68, 0xaa, 0x3f, 0x8d, 0x5d,
	0x83, 0x00, 0x8c, 0xdd, 0xb6, 0x3d, 0x9f, 0xba, 0xdd, 0xda, 0xcd, 0xb9, 0xfb, 0xb3, 0xdb, 0x1e,
	0xdf, 0xe9, 0x6f, 0xce, 0x3b, 0xe1, 0xee, 0xb5, 0x30, 0xa2, 0x81, 0xc8, 0xb8, 0xd7, 0x44, 0xc6,
	0xbd, 0x16, 0x6d, 0x5e, 0x4b, 0x33, 0xef, 0xab, 0xd1, 0xe6, 0xe6, 0x18, 0xfe, 0x97, 0xfd, 0xc0,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x42, 0x48, 0x48, 0x1e, 0x1f, 0x00, 0x00,
}
