// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package router

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/openziti/edge/rest_model"
)

// NewUpdateTransitRouterParams creates a new UpdateTransitRouterParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateTransitRouterParams() *UpdateTransitRouterParams {
	return &UpdateTransitRouterParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateTransitRouterParamsWithTimeout creates a new UpdateTransitRouterParams object
// with the ability to set a timeout on a request.
func NewUpdateTransitRouterParamsWithTimeout(timeout time.Duration) *UpdateTransitRouterParams {
	return &UpdateTransitRouterParams{
		timeout: timeout,
	}
}

// NewUpdateTransitRouterParamsWithContext creates a new UpdateTransitRouterParams object
// with the ability to set a context for a request.
func NewUpdateTransitRouterParamsWithContext(ctx context.Context) *UpdateTransitRouterParams {
	return &UpdateTransitRouterParams{
		Context: ctx,
	}
}

// NewUpdateTransitRouterParamsWithHTTPClient creates a new UpdateTransitRouterParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateTransitRouterParamsWithHTTPClient(client *http.Client) *UpdateTransitRouterParams {
	return &UpdateTransitRouterParams{
		HTTPClient: client,
	}
}

/* UpdateTransitRouterParams contains all the parameters to send to the API endpoint
   for the update transit router operation.

   Typically these are written to a http.Request.
*/
type UpdateTransitRouterParams struct {

	/* ID.

	   The id of the requested resource
	*/
	ID string

	/* Router.

	   A router update object
	*/
	Router *rest_model.RouterUpdate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update transit router params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateTransitRouterParams) WithDefaults() *UpdateTransitRouterParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update transit router params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateTransitRouterParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update transit router params
func (o *UpdateTransitRouterParams) WithTimeout(timeout time.Duration) *UpdateTransitRouterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update transit router params
func (o *UpdateTransitRouterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update transit router params
func (o *UpdateTransitRouterParams) WithContext(ctx context.Context) *UpdateTransitRouterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update transit router params
func (o *UpdateTransitRouterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update transit router params
func (o *UpdateTransitRouterParams) WithHTTPClient(client *http.Client) *UpdateTransitRouterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update transit router params
func (o *UpdateTransitRouterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update transit router params
func (o *UpdateTransitRouterParams) WithID(id string) *UpdateTransitRouterParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update transit router params
func (o *UpdateTransitRouterParams) SetID(id string) {
	o.ID = id
}

// WithRouter adds the router to the update transit router params
func (o *UpdateTransitRouterParams) WithRouter(router *rest_model.RouterUpdate) *UpdateTransitRouterParams {
	o.SetRouter(router)
	return o
}

// SetRouter adds the router to the update transit router params
func (o *UpdateTransitRouterParams) SetRouter(router *rest_model.RouterUpdate) {
	o.Router = router
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateTransitRouterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Router != nil {
		if err := r.SetBodyParam(o.Router); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
