// Code generated by ziti-ci. DO NOT EDIT.

package version

const (
	Version   = "v0.9.3"
	Revision  = "582a3d0a6013"
	Branch    = "update-dependency"
	BuildUser = "Travis CI User"
	BuildDate = "2020-02-13 20:14:45"
)
