// Code generated by ziti-ci. DO NOT EDIT.

package version

const (
	Version   = "v0.14.9"
	Revision  = "796e849593be"
	Branch    = "master"
	BuildUser = "Travis CI User"
	BuildDate = "2020-06-04 15:48:09"
)
