// Code generated by ziti-ci. DO NOT EDIT.

package version

const (
	Version   = "v0.13.4"
	Revision  = "ca4a38820769"
	Branch    = "master"
	BuildUser = "Travis CI User"
	BuildDate = "2020-04-22 18:16:56"
)
