// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openziti/edge/rest_model"
)

// GetIdentityPostureDataFailedServiceRequestsReader is a Reader for the GetIdentityPostureDataFailedServiceRequests structure.
type GetIdentityPostureDataFailedServiceRequestsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIdentityPostureDataFailedServiceRequestsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetIdentityPostureDataFailedServiceRequestsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetIdentityPostureDataFailedServiceRequestsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetIdentityPostureDataFailedServiceRequestsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetIdentityPostureDataFailedServiceRequestsOK creates a GetIdentityPostureDataFailedServiceRequestsOK with default headers values
func NewGetIdentityPostureDataFailedServiceRequestsOK() *GetIdentityPostureDataFailedServiceRequestsOK {
	return &GetIdentityPostureDataFailedServiceRequestsOK{}
}

/*GetIdentityPostureDataFailedServiceRequestsOK handles this case with default header values.

Returns a list of service request failures
*/
type GetIdentityPostureDataFailedServiceRequestsOK struct {
	Payload *rest_model.GetIdentityPostureDataFailedServiceRequestEnvelope
}

func (o *GetIdentityPostureDataFailedServiceRequestsOK) Error() string {
	return fmt.Sprintf("[GET /identities/{id}/posture-data/failed-service-requests][%d] getIdentityPostureDataFailedServiceRequestsOK  %+v", 200, o.Payload)
}

func (o *GetIdentityPostureDataFailedServiceRequestsOK) GetPayload() *rest_model.GetIdentityPostureDataFailedServiceRequestEnvelope {
	return o.Payload
}

func (o *GetIdentityPostureDataFailedServiceRequestsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.GetIdentityPostureDataFailedServiceRequestEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIdentityPostureDataFailedServiceRequestsUnauthorized creates a GetIdentityPostureDataFailedServiceRequestsUnauthorized with default headers values
func NewGetIdentityPostureDataFailedServiceRequestsUnauthorized() *GetIdentityPostureDataFailedServiceRequestsUnauthorized {
	return &GetIdentityPostureDataFailedServiceRequestsUnauthorized{}
}

/*GetIdentityPostureDataFailedServiceRequestsUnauthorized handles this case with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type GetIdentityPostureDataFailedServiceRequestsUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *GetIdentityPostureDataFailedServiceRequestsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /identities/{id}/posture-data/failed-service-requests][%d] getIdentityPostureDataFailedServiceRequestsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetIdentityPostureDataFailedServiceRequestsUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *GetIdentityPostureDataFailedServiceRequestsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIdentityPostureDataFailedServiceRequestsNotFound creates a GetIdentityPostureDataFailedServiceRequestsNotFound with default headers values
func NewGetIdentityPostureDataFailedServiceRequestsNotFound() *GetIdentityPostureDataFailedServiceRequestsNotFound {
	return &GetIdentityPostureDataFailedServiceRequestsNotFound{}
}

/*GetIdentityPostureDataFailedServiceRequestsNotFound handles this case with default header values.

The requested resource does not exist
*/
type GetIdentityPostureDataFailedServiceRequestsNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *GetIdentityPostureDataFailedServiceRequestsNotFound) Error() string {
	return fmt.Sprintf("[GET /identities/{id}/posture-data/failed-service-requests][%d] getIdentityPostureDataFailedServiceRequestsNotFound  %+v", 404, o.Payload)
}

func (o *GetIdentityPostureDataFailedServiceRequestsNotFound) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *GetIdentityPostureDataFailedServiceRequestsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
