// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/openziti/ziti/controller/rest_model"
)

// NewClusterMemberRemoveParams creates a new ClusterMemberRemoveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewClusterMemberRemoveParams() *ClusterMemberRemoveParams {
	return &ClusterMemberRemoveParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewClusterMemberRemoveParamsWithTimeout creates a new ClusterMemberRemoveParams object
// with the ability to set a timeout on a request.
func NewClusterMemberRemoveParamsWithTimeout(timeout time.Duration) *ClusterMemberRemoveParams {
	return &ClusterMemberRemoveParams{
		timeout: timeout,
	}
}

// NewClusterMemberRemoveParamsWithContext creates a new ClusterMemberRemoveParams object
// with the ability to set a context for a request.
func NewClusterMemberRemoveParamsWithContext(ctx context.Context) *ClusterMemberRemoveParams {
	return &ClusterMemberRemoveParams{
		Context: ctx,
	}
}

// NewClusterMemberRemoveParamsWithHTTPClient creates a new ClusterMemberRemoveParams object
// with the ability to set a custom HTTPClient for a request.
func NewClusterMemberRemoveParamsWithHTTPClient(client *http.Client) *ClusterMemberRemoveParams {
	return &ClusterMemberRemoveParams{
		HTTPClient: client,
	}
}

/* ClusterMemberRemoveParams contains all the parameters to send to the API endpoint
   for the cluster member remove operation.

   Typically these are written to a http.Request.
*/
type ClusterMemberRemoveParams struct {

	/* Member.

	   member parameters
	*/
	Member *rest_model.ClusterMemberRemove

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cluster member remove params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClusterMemberRemoveParams) WithDefaults() *ClusterMemberRemoveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cluster member remove params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClusterMemberRemoveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cluster member remove params
func (o *ClusterMemberRemoveParams) WithTimeout(timeout time.Duration) *ClusterMemberRemoveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cluster member remove params
func (o *ClusterMemberRemoveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cluster member remove params
func (o *ClusterMemberRemoveParams) WithContext(ctx context.Context) *ClusterMemberRemoveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cluster member remove params
func (o *ClusterMemberRemoveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cluster member remove params
func (o *ClusterMemberRemoveParams) WithHTTPClient(client *http.Client) *ClusterMemberRemoveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cluster member remove params
func (o *ClusterMemberRemoveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMember adds the member to the cluster member remove params
func (o *ClusterMemberRemoveParams) WithMember(member *rest_model.ClusterMemberRemove) *ClusterMemberRemoveParams {
	o.SetMember(member)
	return o
}

// SetMember adds the member to the cluster member remove params
func (o *ClusterMemberRemoveParams) SetMember(member *rest_model.ClusterMemberRemove) {
	o.Member = member
}

// WriteToRequest writes these params to a swagger request
func (o *ClusterMemberRemoveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Member != nil {
		if err := r.SetBodyParam(o.Member); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
