name: Add to Triage Project

on:
  issues:
    types: [ opened ]
  pull_request_target:
    types: [ opened ]

permissions: {}

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check author and add to project
        if: >-
          github.actor != 'dependabot[bot]' &&
          !contains(fromJson('["andrewpmartinez", "dovholuknf","ekoby","michaelquigley", "mikegorman-nf", "plorenz", "qrkourier","scarey","smilindave26"]'), github.actor)
        uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd  # v2.0.0
        with:
          project-url: https://github.com/orgs/openziti/projects/38
          github-token: ${{ secrets.GH_CI_KEY }}
